// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.

#ifndef NAALP_FFI_H
#define NAALP_FFI_H

/* Auto-generated by cbindgen from impl/rust/naalp-ffi/src/lib.rs. Do not edit by hand; edit the Rust source and regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Status codes returned by every `naalp_*` function that can fail. `Ok` (0) means success;
 every other value is negative and names a specific, real failure the underlying SDK
 raised (mirrored 1:1 from the `kind` string of `naalp::cose::Error` / `naalp::cbor::Error`
 — the same fail-closed named errors the conformance-graded core returns; this crate
 invents no new error semantics). `InvalidArgument` fires only for an FFI-boundary problem
 (a null pointer where one is required, a seed of the wrong length) detected before any
 SDK call. `UnknownSdkError` fires only if the underlying SDK raises an error `kind` this
 crate has not (yet) mapped — never silently reported as a different, more specific code.
 `Internal` fires only if a Rust panic was caught at the FFI boundary; no code path in this
 crate is known to panic (see the panic-containment note above).
 */
enum NaalpStatus
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    Ok = 0,
    InvalidArgument = -1,
    UnknownKind = -2,
    EffectRequired = -3,
    Malformed = -4,
    ContentIdMismatch = -5,
    HeaderBodyMismatch = -6,
    UnknownCriticalExt = -7,
    RangeError = -8,
    UnsupportedVersion = -9,
    WrongAudience = -10,
    TooLarge = -11,
    TooManyCauses = -12,
    TooManyExtensions = -13,
    RotationUnauthorized = -14,
    UnknownAlg = -15,
    ProfileDowngrade = -16,
    HybridIncomplete = -17,
    BadSignature = -18,
    KeyAlgMismatch = -19,
    CompositeRefused = -20,
    SuiteMismatch = -21,
    EffectDeclarationMismatch = -22,
    NonCanonical = -23,
    DepthExceeded = -24,
    Unencodable = -25,
    Internal = -98,
    UnknownSdkError = -99,
};
#if __STDC_VERSION__ >= 202311L
typedef enum NaalpStatus NaalpStatus;
#else
typedef int32_t NaalpStatus;
#endif // __STDC_VERSION__ >= 202311L

/*
 A callee-allocated byte buffer returned by [`naalp_sign`], [`naalp_verify`],
 [`naalp_content_id`], and [`naalp_signer_id`]. `ptr` is `NULL` and `len` is `0` when the
 buffer holds nothing — either because the call that would have filled it returned a
 non-`Ok` [`NaalpStatus`], or because [`naalp_free`] already released it.
 */
typedef struct {
    uint8_t *ptr;
    uintptr_t len;
} NaalpBuffer;

/*
 Signs `body` as a `(channel, kind)` N-AALP object under the Public profile, delegating to
 [`naalp::naalpcore::sign`]. `body` is wrapped as an opaque CBOR byte-string (`bstr`)
 payload — this crate introduces no CBOR map/array-construction API; a caller needing a
 structured (map/array/text) body should build the object with the Rust or another
 language SDK directly, or via [`naalp_content_id`]'s pre-encoded-value path.

 - `seed`/`seed_len`: exactly 32 bytes (a FIPS 204 ML-DSA-65 key-generation seed). Any
   other length is [`NaalpStatus::InvalidArgument`].
 - `channel`/`kind`: the frozen registry `(channel, kind)` this object belongs to.
 - `body`/`body_len`: the caller's opaque payload; `body` may be null only if `body_len`
   is `0`.
 - `out`: on [`NaalpStatus::Ok`], receives a callee-allocated buffer holding the signed,
   deterministic-CBOR COSE_Sign1 object bytes. The caller MUST release it with
   [`naalp_free`] exactly once. On any other return, `*out` is zeroed.

 Never panics; a Rust panic caught internally is reported as [`NaalpStatus::Internal`].
 */
NaalpStatus naalp_sign(const uint8_t *seed,
                       uintptr_t seed_len,
                       uint64_t channel,
                       uint64_t kind,
                       const uint8_t *body,
                       uintptr_t body_len,
                       NaalpBuffer *out);

/*
 Verifies a signed N-AALP object offline under the Public profile, delegating to
 [`naalp::naalpcore::verify`].

 - `pubkey`/`pubkey_len`: the raw ML-DSA-65 public-key bytes (1952 bytes) of the expected
   signer.
 - `obj`/`obj_len`: the signed object bytes.
 - `out_channel`/`out_kind`/`out_effect`: on [`NaalpStatus::Ok`], receive the object's
   decoded `(channel, kind, effect)`.
 - `out_body`: on [`NaalpStatus::Ok`], receives a callee-allocated buffer holding the
   object's body. If the body is the opaque `bstr` shape [`naalp_sign`] produces, `out_body`
   holds exactly those original bytes and `*out_body_is_raw_bstr` is `1`. If the object was
   produced by another SDK with a different body shape (a CBOR map, array, or text value),
   `out_body` instead holds that value's own canonical CBOR encoding and
   `*out_body_is_raw_bstr` is `0` — no information is lost either way.
 - `out_signer_id`: on [`NaalpStatus::Ok`], receives a callee-allocated buffer holding the
   object's self-certifying signer id, as UTF-8 bytes (not NUL-terminated).

 All six output pointers must be non-null (each is required to report part of a verified
 object); a null pointer among them is [`NaalpStatus::InvalidArgument`] before any SDK
 call. On any non-`Ok` return, `*out_body` and `*out_signer_id` are zeroed and the scalar
 outputs are left untouched.

 Never panics; a Rust panic caught internally is reported as [`NaalpStatus::Internal`].
 */
NaalpStatus naalp_verify(const uint8_t *pubkey,
                         uintptr_t pubkey_len,
                         const uint8_t *obj,
                         uintptr_t obj_len,
                         uint64_t *out_channel,
                         uint64_t *out_kind,
                         uint64_t *out_effect,
                         NaalpBuffer *out_body,
                         uint8_t *out_body_is_raw_bstr,
                         NaalpBuffer *out_signer_id);

/*
 The object content-id of a pre-encoded, canonical-CBOR value with field 1 (the id) already
 omitted (design.md §2.3), delegating to [`naalp::naalpcore::content_id`]. This mirrors the
 Rust facade exactly: it performs no encoding of its own beyond decoding
 `value_cbor`/`value_cbor_len`, which MUST already be exactly one canonical-CBOR-encoded
 item (e.g. an object map with field 1 omitted, built by the caller's own SDK) — this
 function introduces no new wire format and constructs nothing on the caller's behalf.

 - `out_id`: on [`NaalpStatus::Ok`], receives a callee-allocated 50-byte buffer
   (`0x20 0x30` || 48-byte SHA-384 digest — a fixed length, but returned as a `NaalpBuffer`
   for a uniform ownership contract with the other three functions). The caller MUST
   release it with [`naalp_free`] exactly once.

 A `value_cbor` that fails to decode as one canonical CBOR item returns the specific
 decode-error [`NaalpStatus`] (e.g. [`NaalpStatus::NonCanonical`]) rather than
 [`NaalpStatus::Malformed`], since the two are distinct, real, named SDK errors.

 Never panics; a Rust panic caught internally is reported as [`NaalpStatus::Internal`].
 */
NaalpStatus naalp_content_id(const uint8_t *value_cbor,
                             uintptr_t value_cbor_len,
                             NaalpBuffer *out_id);

/*
 The self-certifying signer id derived from `(alg, pubkey)` alone (design.md §5.1),
 delegating to [`naalp::naalpcore::signer_id`]. `alg` must be `-49` (ML-DSA-65) or `-50`
 (ML-DSA-87, RFC 9964); any other value is the SDK's own [`NaalpStatus::UnknownAlg`] before
 any digest is computed.

 - `out_id`: on [`NaalpStatus::Ok`], receives a callee-allocated buffer holding the signer
   id as UTF-8 bytes (not NUL-terminated). The caller MUST release it with [`naalp_free`]
   exactly once.

 Never panics; a Rust panic caught internally is reported as [`NaalpStatus::Internal`].
 */
NaalpStatus naalp_signer_id(int64_t alg,
                            const uint8_t *pubkey,
                            uintptr_t pubkey_len,
                            NaalpBuffer *out_id);

/*
 Releases a [`NaalpBuffer`] previously filled by [`naalp_sign`], [`naalp_verify`],
 [`naalp_content_id`], or [`naalp_signer_id`]. Safe to call on a null `buf` pointer or on a
 zeroed buffer (both are no-ops). The caller MUST call this exactly once per filled buffer;
 calling it twice on the same filled buffer, or on a buffer this library did not allocate,
 is undefined behavior — the same contract as C's `free()`. After a successful free, `*buf`
 is zeroed, so a second call on the same `buf` pointer (not a copy of its former contents)
 is safe.

 Never panics.
 */
void naalp_free(NaalpBuffer *buf);

#endif  /* NAALP_FFI_H */
