# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift."""

FIELD_ID = 1
FIELD_KIND = 2
FIELD_CHANNEL = 3
FIELD_TIER = 4
FIELD_SIGNER = 5
FIELD_CREATED = 6
FIELD_EFFECT = 7
FIELD_CAUSES = 8
FIELD_PROFILE = 9
FIELD_BODY = 10
FIELD_EXT = 11
FIELD_CEXT = 12
FIELD_AUDIENCE = 13
FIELD_SUITE = 14

NAALP_VERSION = 2
_HEADER_LABEL = "naalp"

# Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
MAX_OBJECT_SIZE = 1048576
MAX_CAUSES = 1024
MAX_EXT = 64
MAX_CEXT = 64
MAX_NESTING_DEPTH = 16
MAX_STREAM_CHUNKS = 1048576
