# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""Repo-relative path helpers for the naalp-mcp-bridge test suite. No absolute paths -- walks
upward from this file, mirroring naalp_mcp_bridge._bootstrap and
ecosystem/naalp-bundle/tests/_paths.py's convention. READ-ONLY: this package writes nothing
outside ecosystem/naalp-mcp-bridge/ (the hard scope fence)."""
import json
import os


def _find_repo_root(start):
    d = os.path.abspath(start)
    for _ in range(8):
        if os.path.isfile(os.path.join(d, "vectors", "mcp", "cases.json")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    raise RuntimeError("could not locate the naalp_draft-01 repo root "
                        "(vectors/mcp/cases.json) by walking up from %r" % start)


REPO_ROOT = _find_repo_root(os.path.dirname(os.path.abspath(__file__)))


def load_mcp_cases():
    """Independently load vectors/mcp/cases.json -- the F3 non-circular oracle for the
    NAALP-MCP binding profile (design.md Sec.19; generated by tools/mcp_oracle.py from the MCP
    ToolAnnotations contract read from the MCP specification, cross-validated against the closed
    effect lattice, NEVER from impl/python or from naalp_mcp_bridge). Returns the parsed JSON
    dict unchanged."""
    path = os.path.join(REPO_ROOT, "vectors", "mcp", "cases.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)
