# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
Isolation demonstration (A9) for the N-AALP blessed deterministic-CBOR codec binding:
concrete input -> concrete output, independent of any other ecosystem component (no HITL
interceptor, no semantic validator, no N-PAMP transport) -- just naalp_codec called
directly, plus the Part-1 envelope it wraps.

Run:  python examples/isolation_demo.py   (from ecosystem/naalp-codec/)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from naalp_codec import (  # noqa: E402  (puts impl/python on sys.path)
    A, B, M, NonCanonical, T, U, canonical_bytes, content_id, decode, encode, verify_roundtrip,
)
from naalp import envelope  # noqa: E402

# The pinned "minimal" vector from vectors/cbor/cases.json (the C1 codec's own independent
# oracle corpus, generated by tools/cbor_oracle.py): a Control/Hello object, signer
# "SIGNER_A", body text "hello". Hardcoded here (not read from the vectors file) so this
# demo runs standalone with no dependency beyond naalp_codec + naalp.
_SIGNER_A = bytes.fromhex("5349474e45525f41")
_MINIMAL_BODY_NO1_HEX = (
    "a902000300040005485349474e45525f41061b0000019f9a4a7a000700088009010a6568656c6c6f"
)
_MINIMAL_ID_HEX = (
    "2030450ceccc1d43b1c9bd098530ca64cb1b1c458d7244972dfca49a824b4290f05bca3d8dd65f43e"
    "d6c5204ee8e76f402fc"
)
_MINIMAL_FULL_HEX = (
    "aa0158322030450ceccc1d43b1c9bd098530ca64cb1b1c458d7244972dfca49a824b4290f05bca3d8"
    "dd65f43ed6c5204ee8e76f402fc02000300040005485349474e45525f41061b0000019f9a4a7a0007"
    "00088009010a6568656c6c6f"
)


def main():
    print("=== N-AALP blessed deterministic-CBOR codec binding -- isolation demo ===\n")

    # 1. Build the "minimal" object body directly with naalp_codec's own public value
    #    classes (U/T/B/A/M) -- no naalp.cbor import needed by a caller.
    body = M([
        (U(2), U(0)),                       # kind
        (U(3), U(0)),                       # channel
        (U(4), U(0)),                       # tier
        (U(5), B(_SIGNER_A)),                # signer
        (U(6), U(1785000000000)),           # created
        (U(7), U(0)),                       # effect
        (U(8), A([])),                      # causes
        (U(9), U(1)),                       # profile
        (U(10), T("hello")),                # body
    ])
    encoded = encode(body)
    print("1. Constructed body encodes to the pinned 'minimal' vector bytes:")
    print("   match =", encoded == bytes.fromhex(_MINIMAL_BODY_NO1_HEX))
    assert encoded == bytes.fromhex(_MINIMAL_BODY_NO1_HEX)

    # 2. content_id() over that same body matches the pinned id_hex.
    cid = content_id(body)
    print("\n2. content_id() matches the pinned reference content-id:")
    print("   match =", cid == bytes.fromhex(_MINIMAL_ID_HEX))
    assert cid == bytes.fromhex(_MINIMAL_ID_HEX)

    # 3. canonical_bytes() is the same call as encode() -- the "one true encoding" guarantee.
    print("\n3. canonical_bytes() agrees with encode():", canonical_bytes(body) == encoded)
    assert canonical_bytes(body) == encoded

    # 4. Round-trip: decode the pinned bytes, re-encode, get the identical bytes back.
    decoded = decode(encoded)
    re_encoded = encode(decoded)
    print("\n4. Round trip (decode -> encode) reproduces the original bytes:",
          re_encoded == encoded)
    assert re_encoded == encoded
    assert verify_roundtrip(body) is True

    # 5. The same object built through the Part-1 envelope SDK (naalp.envelope.Object)
    #    produces the SAME full signed-body bytes and the SAME content id -- this is R7's
    #    actual point: a caller using either the raw naalp_codec value classes OR the
    #    higher-level envelope.Object gets byte-identical results, because both paths end
    #    at the one blessed codec underneath.
    obj = envelope.Object(
        kind=0, channel=0, signer=_SIGNER_A, created=1785000000000, effect=0,
        profile=1, body=T("hello"),
    )
    obj.id = obj.content_id()
    full_bytes = encode(obj._body_map(True))
    print("\n5. Part-1 envelope.Object built independently matches both pinned vectors:")
    print("   content_id match =", obj.id == bytes.fromhex(_MINIMAL_ID_HEX))
    print("   full-body match  =", full_bytes == bytes.fromhex(_MINIMAL_FULL_HEX))
    assert obj.id == bytes.fromhex(_MINIMAL_ID_HEX)
    assert full_bytes == bytes.fromhex(_MINIMAL_FULL_HEX)

    # 6. Fail-closed: a hallucinated float value in an ext-shaped map is rejected with the
    #    registered NonCanonical error -- no sanitized bytes are ever produced.
    hallucinated = M([(U(10), T("confidence")), (U(99), 0.87)])
    print("\n6. Encoding a body with a bare float value:")
    try:
        encode(hallucinated)
        raised = False
    except NonCanonical as e:
        raised = True
        print("   raised NonCanonical:", e)
    assert raised

    # 7. Fail-closed: a duplicate map key is rejected the same way (Part-1's own encode-time
    #    sort-then-dedupe check, reached unmodified through this binding).
    dup_key = M([(U(1), T("a")), (U(1), T("b"))])
    print("\n7. Encoding a body with a duplicate map key:")
    try:
        encode(dup_key)
        raised = False
    except NonCanonical as e:
        raised = True
        print("   raised NonCanonical:", e)
    assert raised

    # 8. Fail-closed: a non-canonical byte string received off the wire (a non-shortest-form
    #    integer head) is rejected by decode() before any value is materialized.
    non_shortest = bytes.fromhex("1800")  # uint 0 encoded in the 2-byte form, not 1-byte
    print("\n8. Decoding a non-shortest-form integer (0x1800):")
    try:
        decode(non_shortest)
        raised = False
    except NonCanonical as e:
        raised = True
        print("   raised NonCanonical:", e)
    assert raised

    print("\n=== all isolation assertions held ===")


if __name__ == "__main__":
    main()
