<!-- Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>naalp-adapter-csharp</AssemblyName>
    <RootNamespace>Naalp.Adapter</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../impl/csharp/Bubblefish.Naalp.csproj" />
  </ItemGroup>

</Project>
