// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.
namespace Naalp
{
    public static partial class Envelope
    {
        // object body field numbers (design.md §2.1)
        public const int FieldId = 1;
        public const int FieldKind = 2;
        public const int FieldChannel = 3;
        public const int FieldTier = 4;
        public const int FieldSigner = 5;
        public const int FieldCreated = 6;
        public const int FieldEffect = 7;
        public const int FieldCauses = 8;
        public const int FieldProfile = 9;
        public const int FieldBody = 10;
        public const int FieldExt = 11;
        public const int FieldCext = 12;
        public const int FieldAudience = 13;
        public const int FieldSuite = 14;

        public const int NaalpVersion = 2;
        private const string HeaderLabel = "naalp";
        // Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
        public const long MaxObjectSize = 1048576;
        public const long MaxCauses = 1024;
        public const long MaxExt = 64;
        public const long MaxCext = 64;
        public const long MaxNestingDepth = 16;
        public const long MaxStreamChunks = 1048576;
    }
}
