# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""Repo-relative path + pinned-corpus helpers for the naalp-codec test suite. No absolute
paths -- walks upward from this file, mirroring naalp_codec._bootstrap and
ecosystem/naalp-validator/tests/_paths.py's convention."""
import json
import os


def _find_repo_root(start):
    d = os.path.abspath(start)
    for _ in range(8):
        if os.path.isfile(os.path.join(d, "vectors", "cbor", "cases.json")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    raise RuntimeError("could not locate the naalp_draft-01 repo root (vectors/cbor/cases.json) "
                        "by walking up from %r" % start)


REPO_ROOT = _find_repo_root(os.path.dirname(os.path.abspath(__file__)))


def load_cbor_cases():
    """Independently load vectors/cbor/cases.json -- the F3 non-circular oracle for the C1
    deterministic-CBOR codec (generated by tools/cbor_oracle.py, a from-scratch constructor
    written against RFC 8949 + FIPS 180-4 that shares no code with impl/python/naalp/cbor.py
    or with naalp_codec). Returns the parsed JSON dict unchanged; callers use its
    'positives' / 'negatives' entries directly. Never modified here (read-only)."""
    path = os.path.join(REPO_ROOT, "vectors", "cbor", "cases.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def value_from_tagged(codec, tagged):
    """Rebuild a cbor value object (via naalp_codec's own public value classes) from the
    (type_tag, payload) shape vectors/cbor/cases.json uses for its 'obj_without_id' field
    values. This is a mechanical, from-scratch interpreter of that JSON shape -- it imports
    nothing from tools/cbor_oracle.py and performs no encoding itself, so building the
    expected VALUE here does not borrow the oracle's own construction code; only the oracle's
    pre-computed *_hex strings (read by load_cbor_cases above) serve as the expected bytes."""
    kind, payload = tagged
    if kind == "u":
        return codec.U(payload)
    if kind == "n":
        return codec.N(payload)
    if kind == "b":
        return codec.B(bytes.fromhex(payload))
    if kind == "s":
        return codec.T(payload)
    if kind == "arr":
        return codec.A([value_from_tagged(codec, item) for item in payload])
    if kind == "map":
        return codec.M([(value_from_tagged(codec, k), value_from_tagged(codec, v)) for k, v in payload])
    raise ValueError("unknown tagged-value kind %r in vectors/cbor/cases.json" % (kind,))


def object_body_map(codec, obj_without_id):
    """Rebuild the field-numbered body map (field-number string -> tagged value) from a
    positives[].obj_without_id entry into a single codec.M. Ascending field-number order is
    used for readability only -- the codec's own canonical sort (by encoded key bytes) makes
    insertion order irrelevant to the resulting encoded bytes."""
    pairs = []
    for k in sorted(obj_without_id.keys(), key=int):
        pairs.append((codec.U(int(k)), value_from_tagged(codec, obj_without_id[k])))
    return codec.M(pairs)
