# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
Known-answer + fail-closed tests for the N-AALP blessed deterministic-CBOR codec binding
(naalp_codec.codec), Part-2 ecosystem task E0.3, requirement R7.

Non-circularity (F3): every expected byte string in `ByteIdentityAgainstPinnedCorpus` comes
from `vectors/cbor/cases.json` -- generated by `tools/cbor_oracle.py`, a from-scratch
constructor written against RFC 8949 sec.4.2.1 + FIPS 180-4 that shares no code with
`impl/python/naalp/cbor.py` or with `naalp_codec` -- never from the binding under test.
`tests/_paths.py` rebuilds the expected VALUE objects from that file's tagged JSON shape
independently of `tools/cbor_oracle.py`'s own construction code; only its pre-computed
`*_hex` strings serve as the expected bytes.

Coverage: round-trip fidelity (decode a pinned vector, re-encode, bytes match) and
construct-then-encode-matches-pinned-bytes for >=3 real object vectors; every `negatives`
entry in the pinned corpus (duplicate key, float, non-shortest int, out-of-order keys,
indefinite-length array) rejected with the registered `NonCanonical` error; the binding's
own encode-side float guard and duplicate-key delegation; and the two functions this
binding adds beyond a bare re-export (`content_id`, `verify_roundtrip`), each proven to
perform real, input-dependent work rather than a constant/stubbed answer.

Run:  <python> -m pytest -v tests/test_codec.py
      (from ecosystem/naalp-codec/, with PYTHONDONTWRITEBYTECODE=1; on a Windows checkout
      where a bare "python" resolves to a Store stub, invoke the real interpreter by its
      own full path instead.)
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _paths  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import naalp_codec as codec  # noqa: E402

_CASES = _paths.load_cbor_cases()
_POSITIVES = {p["name"]: p for p in _CASES["positives"]}
_NEGATIVES = {n["name"]: n for n in _CASES["negatives"]}


class ByteIdentityAgainstPinnedCorpus(unittest.TestCase):
    """The load-bearing conformance test: this binding's encode()/decode() must reproduce
    the pinned, independently-generated oracle bytes exactly -- both directions."""

    def test_round_trip_minimal(self):
        self._round_trip("minimal")

    def test_round_trip_nested(self):
        self._round_trip("nested")

    def test_round_trip_absent_ext(self):
        self._round_trip("absent_ext")

    def test_round_trip_empty_ext(self):
        self._round_trip("empty_ext")

    def _round_trip(self, name):
        """decode(pinned bytes) -> value -> encode(value) must reproduce the exact pinned
        bytes (round-trip fidelity: the codec accepts only its own canonical form back)."""
        vec = _POSITIVES[name]
        original = bytes.fromhex(vec["body_no1_hex"])
        value = codec.decode(original)
        re_encoded = codec.encode(value)
        self.assertEqual(re_encoded, original,
                          "round-trip of pinned vector %r did not reproduce its bytes" % name)

    def test_construct_matches_minimal(self):
        self._construct_matches("minimal")

    def test_construct_matches_nested(self):
        self._construct_matches("nested")

    def test_construct_matches_absent_ext(self):
        self._construct_matches("absent_ext")

    def _construct_matches(self, name):
        """Build the object body from the pinned vector's tagged field description (using
        ONLY naalp_codec's public value classes -- U/T/B/A/M) and confirm encode() reproduces
        the pinned bytes exactly: a third-party caller using nothing but this binding's
        public surface produces the reference bytes for a given logical object."""
        vec = _POSITIVES[name]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        encoded = codec.encode(value)
        self.assertEqual(encoded, bytes.fromhex(vec["body_no1_hex"]),
                          "constructed encoding of vector %r did not match the pinned bytes" % name)

    def test_content_id_matches_pinned_minimal(self):
        """content_id() over the constructed 'minimal' body (field 1/id excluded, exactly
        what body_no1_hex represents) must equal the pinned id_hex -- the literal proof R7
        asks for: a body built through this binding's own public API produces the reference
        content id."""
        vec = _POSITIVES["minimal"]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        self.assertEqual(codec.content_id(value), bytes.fromhex(vec["id_hex"]))

    def test_content_id_matches_pinned_nested(self):
        vec = _POSITIVES["nested"]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        self.assertEqual(codec.content_id(value), bytes.fromhex(vec["id_hex"]))

    def test_content_id_over_already_encoded_bytes_agrees_with_over_value(self):
        """content_id() accepts either a value or already-encoded bytes; both paths must
        agree (they compute the same multihash over the same canonical bytes)."""
        vec = _POSITIVES["minimal"]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        via_value = codec.content_id(value)
        via_bytes = codec.content_id(codec.encode(value))
        self.assertEqual(via_value, via_bytes)
        self.assertEqual(via_value, bytes.fromhex(vec["id_hex"]))


class NegativeVectorsRejectFailClosed(unittest.TestCase):
    """Every `negatives` entry in the pinned corpus must be rejected by decode() with the
    registered error NAME the vector names -- never accepted, never silently 'sanitized'
    into a shorter/reordered/deduplicated form and returned as if valid."""

    def test_every_pinned_negative_is_rejected(self):
        self.assertGreaterEqual(len(_NEGATIVES), 5, "expected the full pinned negative set")
        error_classes = {"NonCanonical": codec.NonCanonical, "DepthExceeded": codec.DepthExceeded}
        for name, vec in _NEGATIVES.items():
            with self.subTest(name=name):
                exc_cls = error_classes[vec["expect"]]
                data = bytes.fromhex(vec["bytes_hex"])
                with self.assertRaises(exc_cls) as ctx:
                    result = codec.decode(data)
                    self.fail("decode() of negative vector %r returned %r instead of "
                              "raising %s" % (name, result, vec["expect"]))
                # No bytes/value are ever produced on a rejection -- the exception IS the
                # entire outcome, so there is nothing left over to have been "sanitized".
                self.assertIsInstance(ctx.exception, exc_cls)

    def test_duplicate_key_named_explicitly(self):
        """The 'duplicate_key' vector (a201000101: a 2-entry map, both keys U(1)) named
        explicitly, per the task's required fail-closed coverage."""
        vec = _NEGATIVES["duplicate_key"]
        with self.assertRaises(codec.NonCanonical):
            codec.decode(bytes.fromhex(vec["bytes_hex"]))

    def test_float_in_body_bytes_named_explicitly(self):
        """The 'float_half' vector (f93e00: a CBOR half-float) named explicitly -- a
        float-bearing body arriving over the wire, rejected as NonCanonical."""
        vec = _NEGATIVES["float_half"]
        with self.assertRaises(codec.NonCanonical):
            codec.decode(bytes.fromhex(vec["bytes_hex"]))

    def test_non_shortest_encoding_named_explicitly(self):
        """The 'int_notshortest' vector (1800: uint 0 encoded in the 2-byte form instead of
        the shortest 1-byte form) named explicitly -- the concrete "non-shortest encoding"
        fail-closed case. (0x41A0 itself is the COSE *protected-header* empty-map pin, a
        rule of the envelope layer, not of the raw deterministic-CBOR value codec this
        binding wraps: b'\\x41\\xa0' decodes as a perfectly canonical 1-byte bstr at the
        codec level, so it is not used here as a negative case -- doing so would be a false
        claim about what this binding rejects.)"""
        vec = _NEGATIVES["int_notshortest"]
        with self.assertRaises(codec.NonCanonical):
            codec.decode(bytes.fromhex(vec["bytes_hex"]))


class EncodeSideFailClosed(unittest.TestCase):
    """Fail-closed behaviour on the ENCODE direction: constructing a value that is invalid
    to put on the wire must raise before any bytes are produced."""

    def test_encode_rejects_bare_float_nested_in_body(self):
        """A body/ext-shaped map carrying a raw Python float value (the 'LLM emitted a
        numeric score as a float' shape) is rejected as NonCanonical -- the binding's own
        value-add over the bare naalp.cbor.encode, which would raise the wrong-named
        TypeError for this input (see codec.py module docstring)."""
        value = codec.M([(codec.U(10), codec.T("confidence")), (codec.U(99), 0.87)])
        with self.assertRaises(codec.NonCanonical):
            codec.encode(value)

    def test_encode_rejects_bare_float_at_top_level(self):
        with self.assertRaises(codec.NonCanonical):
            codec.encode(3.14)

    def test_encode_rejects_bare_float_inside_array(self):
        value = codec.A([codec.U(1), 2.5, codec.T("x")])
        with self.assertRaises(codec.NonCanonical):
            codec.encode(value)

    def test_encode_raises_no_bytes_returned_on_float(self):
        """Confirm the rejection genuinely produces nothing: a caller cannot obtain a
        partial/sanitized byte string by catching the exception and inspecting locals --
        encode() never reaches a `return` statement on this input."""
        sentinel = object()
        result = sentinel
        try:
            result = codec.encode(codec.M([(codec.U(1), 1.0)]))
        except codec.NonCanonical:
            pass
        self.assertIs(result, sentinel, "encode() must not return anything on rejection")

    def test_encode_rejects_duplicate_map_key(self):
        """Part-1's own encode()-time duplicate-key check (sort-then-dedupe), reached
        unmodified through this binding: two U(1) keys in the same map."""
        value = codec.M([(codec.U(1), codec.T("a")), (codec.U(1), codec.T("b"))])
        with self.assertRaises(codec.NonCanonical):
            codec.encode(value)


class ContentIdVariesWithInput(unittest.TestCase):
    """content_id() must be a real, input-dependent computation, not a constant -- the A4
    test applied to this binding's own delegating wrapper."""

    def test_distinct_values_produce_distinct_ids(self):
        v1 = codec.M([(codec.U(2), codec.U(0))])
        v2 = codec.M([(codec.U(2), codec.U(1))])
        self.assertNotEqual(codec.content_id(v1), codec.content_id(v2))

    def test_id_is_48_byte_sha384_multihash_with_registered_prefix(self):
        """content_id format (naalp.cbor.content_id, sec.2.3): 0x20 (sha2-384 multihash
        code), 0x30 (48, the digest length), then the 48-byte SHA-384 digest -- 50 bytes
        total. Checked structurally (not by string-matching a name) against the pinned
        'minimal' id_hex, which is exactly this shape."""
        vec = _POSITIVES["minimal"]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        cid = codec.content_id(value)
        self.assertEqual(len(cid), 50)
        self.assertEqual(cid[0], 0x20)
        self.assertEqual(cid[1], 0x30)
        self.assertEqual(cid, bytes.fromhex(vec["id_hex"]))


class VerifyRoundtripRealWork(unittest.TestCase):
    """verify_roundtrip() must actually perform encode/decode/re-encode and propagate a
    real failure, rather than unconditionally returning True."""

    def test_true_on_a_valid_pinned_value(self):
        vec = _POSITIVES["nested"]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        self.assertTrue(codec.verify_roundtrip(value))

    def test_propagates_type_error_on_a_non_value_input(self):
        """A raw Python int (not a codec.U wrapper) is not a recognised value type at all;
        the real implementation's first step (encode(5)) raises TypeError, and
        verify_roundtrip must let that propagate rather than swallow it and report a
        blanket True."""
        with self.assertRaises(TypeError):
            codec.verify_roundtrip(5)

    def test_propagates_non_canonical_on_a_bare_float(self):
        with self.assertRaises(codec.NonCanonical):
            codec.verify_roundtrip(codec.M([(codec.U(1), 9.9)]))


class CanonicalBytesIsEncodeAlias(unittest.TestCase):
    def test_matches_encode_on_pinned_vector(self):
        vec = _POSITIVES["absent_ext"]
        value = _paths.object_body_map(codec, vec["obj_without_id"])
        self.assertEqual(codec.canonical_bytes(value), codec.encode(value))
        self.assertEqual(codec.canonical_bytes(value), bytes.fromhex(vec["body_no1_hex"]))


class PublicAPISurface(unittest.TestCase):
    """The value-model classes and error types are re-exported directly from naalp_codec
    (not just from naalp_codec.codec), so a caller never needs to import naalp itself."""

    def test_value_classes_reexported(self):
        for name in ("U", "N", "B", "T", "A", "M", "Tag"):
            self.assertTrue(hasattr(codec, name), "naalp_codec.%s missing" % name)

    def test_error_classes_reexported(self):
        self.assertTrue(hasattr(codec, "NonCanonical"))
        self.assertTrue(hasattr(codec, "DepthExceeded"))
        self.assertTrue(issubclass(codec.NonCanonical, ValueError))
        self.assertTrue(issubclass(codec.DepthExceeded, ValueError))

    def test_decode_bounded_rejects_over_depth(self):
        """decode_bounded, unmodified: an item past the given depth is rejected before
        materialization. 5 nested singleton arrays around a leaf, bounded to depth 3."""
        value = codec.A([codec.A([codec.A([codec.A([codec.A([codec.T("leaf")])])])])])
        data = codec.encode(value)
        with self.assertRaises(codec.DepthExceeded):
            codec.decode_bounded(data, 3)
        # The same data decodes fine with headroom.
        self.assertIsNotNone(codec.decode_bounded(data, 10))


if __name__ == "__main__":
    unittest.main()
