export function algLevel(alg: any): any[];
export function profileMinLevel(profile: any): 5 | 3;
export function toBeSignedRaw(protectedHdr: any, payload: any): any;
export function assembleSign1Raw(protectedHdr: any, payload: any, sig: any): any;
export function parseSign1Raw(obj: any): Uint8Array<ArrayBuffer>[];
export function mldsaKeygen(param: any, seed: any): Uint8Array<ArrayBufferLike> & Uint8Array<ArrayBuffer>;
export function mldsaSign(alg: any, seed: any, tbs: any): Uint8Array<ArrayBufferLike> & Uint8Array<ArrayBuffer>;
export function mldsaVerify(alg: any, pk: any, tbs: any, sig: any): boolean;
export function ed25519Sign(seed: any, msg: any): Uint8Array<ArrayBufferLike> & Uint8Array<ArrayBuffer>;
export function ed25519Verify(pk: any, msg: any, sig: any): boolean;
export function coseSign1(alg: any, seed: any, protectedHdr: any, payload: any): any;
export function coseVerify1Raw(alg: any, pk: any, tbs: any, sig: any): boolean;
export function coseVerify1(alg: any, pk: any, obj: any): boolean;
export const ALG_MLDSA65: -49;
export const ALG_MLDSA87: -50;
export const ALG_ED25519: -19;
export const PROFILE_PUBLIC: 1;
export const PROFILE_ENTERPRISE: 2;
export const PROFILE_SOVEREIGN: 3;
export const TAG_SIGN1: 18;
