// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.

export const FIELD_ID = 1;
export const FIELD_KIND = 2;
export const FIELD_CHANNEL = 3;
export const FIELD_TIER = 4;
export const FIELD_SIGNER = 5;
export const FIELD_CREATED = 6;
export const FIELD_EFFECT = 7;
export const FIELD_CAUSES = 8;
export const FIELD_PROFILE = 9;
export const FIELD_BODY = 10;
export const FIELD_EXT = 11;
export const FIELD_CEXT = 12;
export const FIELD_AUDIENCE = 13;
export const FIELD_SUITE = 14;

export const NAALP_VERSION = 2;
export const HEADER_LABEL = 'naalp';

// Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
export const MAX_OBJECT_SIZE = 1048576;
export const MAX_CAUSES = 1024;
export const MAX_EXT = 64;
export const MAX_CEXT = 64;
export const MAX_NESTING_DEPTH = 16;
export const MAX_STREAM_CHUNKS = 1048576;
