// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.
package sh.bubblefish.naalp;

// Object body field numbers (design.md §2.1), naalp-version (§2.5), COSE header label.
final class WireConstants {
    private WireConstants() {}
    public static final int FIELD_ID = 1;
    public static final int FIELD_KIND = 2;
    public static final int FIELD_CHANNEL = 3;
    public static final int FIELD_TIER = 4;
    public static final int FIELD_SIGNER = 5;
    public static final int FIELD_CREATED = 6;
    public static final int FIELD_EFFECT = 7;
    public static final int FIELD_CAUSES = 8;
    public static final int FIELD_PROFILE = 9;
    public static final int FIELD_BODY = 10;
    public static final int FIELD_EXT = 11;
    public static final int FIELD_CEXT = 12;
    public static final int FIELD_AUDIENCE = 13;
    public static final int FIELD_SUITE = 14;
    public static final long NAALP_VERSION = 2;
    public static final String HEADER_LABEL = "naalp";
    // Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
    public static final long MAX_OBJECT_SIZE = 1048576;
    public static final long MAX_CAUSES = 1024;
    public static final long MAX_EXT = 64;
    public static final long MAX_CEXT = 64;
    public static final long MAX_NESTING_DEPTH = 16;
    public static final long MAX_STREAM_CHUNKS = 1048576;
}
