// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.
package sh.bubblefish.naalp

// Object body field numbers (design.md §2.1), naalp-version (§2.5), COSE header label.
const val FIELD_ID = 1L
const val FIELD_KIND = 2L
const val FIELD_CHANNEL = 3L
const val FIELD_TIER = 4L
const val FIELD_SIGNER = 5L
const val FIELD_CREATED = 6L
const val FIELD_EFFECT = 7L
const val FIELD_CAUSES = 8L
const val FIELD_PROFILE = 9L
const val FIELD_BODY = 10L
const val FIELD_EXT = 11L
const val FIELD_CEXT = 12L
const val FIELD_AUDIENCE = 13L
const val FIELD_SUITE = 14L
const val NAALP_VERSION = 2L
const val HEADER_LABEL = "naalp"
// Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
const val MAX_OBJECT_SIZE = 1048576L
const val MAX_CAUSES = 1024L
const val MAX_EXT = 64L
const val MAX_CEXT = 64L
const val MAX_NESTING_DEPTH = 16L
const val MAX_STREAM_CHUNKS = 1048576L
