<?php
// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.
declare(strict_types=1);

namespace Naalp;

/** Object body field numbers (design.md §2.1), naalp-version (§2.5), COSE header label. */
final class WireConstants
{
    public const FIELD_ID = 1;
    public const FIELD_KIND = 2;
    public const FIELD_CHANNEL = 3;
    public const FIELD_TIER = 4;
    public const FIELD_SIGNER = 5;
    public const FIELD_CREATED = 6;
    public const FIELD_EFFECT = 7;
    public const FIELD_CAUSES = 8;
    public const FIELD_PROFILE = 9;
    public const FIELD_BODY = 10;
    public const FIELD_EXT = 11;
    public const FIELD_CEXT = 12;
    public const FIELD_AUDIENCE = 13;
    public const FIELD_SUITE = 14;
    public const NAALP_VERSION = 2;
    public const HEADER_LABEL = "naalp";
    // Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
    public const MAX_OBJECT_SIZE = 1048576;
    public const MAX_CAUSES = 1024;
    public const MAX_EXT = 64;
    public const MAX_CEXT = 64;
    public const MAX_NESTING_DEPTH = 16;
    public const MAX_STREAM_CHUNKS = 1048576;
}
