// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.

// Object body field numbers (design.md §2.1).
public enum EnvelopeField {
    public static let id = 1
    public static let kind = 2
    public static let channel = 3
    public static let tier = 4
    public static let signer = 5
    public static let created = 6
    public static let effect = 7
    public static let causes = 8
    public static let profile = 9
    public static let body = 10
    public static let ext = 11
    public static let cext = 12
    public static let audience = 13
    public static let suite = 14
}

// The protected-header naalp-version (design.md §2.5).
public let NAALP_VERSION: UInt64 = 2

// The COSE protected-header parameter (a text-string label, RFC 9052 §3.1).
let naalpHeaderLabel = "naalp"

// Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
public let MAX_OBJECT_SIZE: UInt64 = 1048576
public let MAX_CAUSES: UInt64 = 1024
public let MAX_EXT: UInt64 = 64
public let MAX_CEXT: UInt64 = 64
public let MAX_NESTING_DEPTH: UInt64 = 16
public let MAX_STREAM_CHUNKS: UInt64 = 1048576
