// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.

package naalpdid

import (
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"testing"
)

// TestBuildAKPJWK_ReproducesRFC9964Example is acceptance criterion 1 from
// design.md addendum E4.1 §(d): pin RFC 9964's own published
// example (Appendix A.1, Figure 3, "ML_DSA_44" — raw_public_key in hex, jwk.pub in
// base64url) as an independent, non-circular oracle vector, and confirm buildAKPJWK
// reproduces the "pub" field byte-for-byte from the SAME raw public key. Neither value
// was generated by this package or by N-AALP's own encoder — both were extracted
// verbatim from the RFC's raw text (see testdata/rfc_vectors.json's "_provenance").
//
// This deliberately does NOT byte-compare the full RFC example JSON object: that example
// is a PRIVATE key JWK (it carries "priv"), which did:jwk's own security rule forbids
// ever using as a DID — so a full-document match against it is not even a legitimate
// target. What is pinned and independently reproducible is the cryptographic
// representation: kty="AKP", alg="ML-DSA-44", and pub=base64url(raw public key).
func TestBuildAKPJWK_ReproducesRFC9964Example(t *testing.T) {
	v := loadRFCVectors(t)
	rawPub, err := hex.DecodeString(v.RFC9964MLDSA44RawPublicKeyHex)
	if err != nil {
		t.Fatalf("decode raw_public_key hex: %v", err)
	}
	if len(rawPub) != 1312 {
		t.Fatalf("RFC 9964 Table 1 states the ML-DSA-44 public key is 1312 bytes; got %d", len(rawPub))
	}

	got := buildAKPJWK("ML-DSA-44", rawPub)

	var parsed akpJWK
	if err := json.Unmarshal(got, &parsed); err != nil {
		t.Fatalf("buildAKPJWK produced invalid JSON: %v", err)
	}
	if parsed.Kty != "AKP" {
		t.Errorf("kty = %q, want AKP (RFC 9964 §8.1.5.1)", parsed.Kty)
	}
	if parsed.Alg != "ML-DSA-44" {
		t.Errorf("alg = %q, want ML-DSA-44 (RFC 9964 §8.1.4.1)", parsed.Alg)
	}
	if parsed.Pub != v.RFC9964MLDSA44JWKPubB64URL {
		t.Errorf("pub field does not byte-match RFC 9964's own published jwk.pub value\n got: %s\nwant: %s", parsed.Pub, v.RFC9964MLDSA44JWKPubB64URL)
	}

	// Independent second check on the same claim, via decode rather than string
	// comparison: base64url-decoding OUR "pub" field must yield exactly the RFC's
	// raw_public_key bytes.
	ourPubBytes, err := base64.RawURLEncoding.DecodeString(parsed.Pub)
	if err != nil {
		t.Fatalf("decode our own pub field: %v", err)
	}
	if string(ourPubBytes) != string(rawPub) {
		t.Fatalf("decoded pub bytes do not equal RFC 9964's raw_public_key bytes")
	}
}

// TestParseAKPJWK_RoundTrip confirms parseAKPJWK is the true inverse of buildAKPJWK for
// both ML-DSA parameter sets N-AALP actually uses, using freshly-constructed (not
// RFC-pinned) key bytes — this is acceptance criterion 2's shape applied at the AKP-JWK
// layer specifically.
func TestParseAKPJWK_RoundTrip(t *testing.T) {
	cases := []struct {
		alg string
		pub []byte
	}{
		{"ML-DSA-65", bytesOfLen(1952, 0x65)},
		{"ML-DSA-87", bytesOfLen(2592, 0x87)},
	}
	for _, c := range cases {
		raw := buildAKPJWK(c.alg, c.pub)
		gotAlg, gotPub, err := parseAKPJWK(raw)
		if err != nil {
			t.Fatalf("parseAKPJWK(%s): %v", c.alg, err)
		}
		if gotAlg != c.alg {
			t.Errorf("alg round-trip: got %q want %q", gotAlg, c.alg)
		}
		if string(gotPub) != string(c.pub) {
			t.Errorf("pub round-trip mismatch for %s", c.alg)
		}
	}
}

// TestParseAKPJWK_RejectsPrivateKey is the fail-closed security property acceptance
// criterion 3 requires generically: a JWK carrying "priv" MUST be rejected whole, never
// silently accepted with the private material simply ignored. This is the check the
// package's witnessed mutation targets (see the E4.1 build report).
func TestParseAKPJWK_RejectsPrivateKey(t *testing.T) {
	raw := []byte(`{"kty":"AKP","alg":"ML-DSA-65","pub":"AAAA","priv":"AAAA"}`)
	_, _, err := parseAKPJWK(raw)
	if err != ErrPrivateKeyJWK {
		t.Fatalf("parseAKPJWK on a private-key JWK: got err=%v, want ErrPrivateKeyJWK", err)
	}
}

func TestParseAKPJWK_RejectsWrongKty(t *testing.T) {
	raw := []byte(`{"kty":"OKP","alg":"ML-DSA-65","pub":"AAAA"}`)
	if _, _, err := parseAKPJWK(raw); err != ErrUnsupportedKty {
		t.Fatalf("got err=%v, want ErrUnsupportedKty", err)
	}
}

func TestParseAKPJWK_RejectsMalformedJSON(t *testing.T) {
	if _, _, err := parseAKPJWK([]byte("not json")); err != ErrMalformedJWK {
		t.Fatalf("got err=%v, want ErrMalformedJWK", err)
	}
}

// bytesOfLen returns a deterministic n-byte slice (not random) so this test's expected
// values are reproducible without a live key generator.
func bytesOfLen(n int, seed byte) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = seed + byte(i)
	}
	return b
}
