// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.

package naalpdid

import (
	"encoding/base64"
	"strings"
	"testing"
)

// TestWrapDIDJWK_ReproducesSpecExample is the F3 non-circular KAT for the wrapping
// mechanism itself: it independently base64url-decodes the did:jwk spec's OWN P-256
// worked example (github.com/quartzjer/did-jwk spec.md, "Examples > P-256", fetched
// 2026-08-31) using the Go standard library directly — NOT unwrapDIDJWK, the function
// under test — and then confirms wrapDIDJWK reproduces the spec's exact literal DID
// string byte-for-byte. The expected value (the DID string) comes entirely from the
// external spec; nothing here was generated by this package.
func TestWrapDIDJWK_ReproducesSpecExample(t *testing.T) {
	v := loadRFCVectors(t)
	rest := strings.TrimPrefix(v.DIDJWKSpecP256DID, didJWKPrefix)
	decoded, err := base64.RawURLEncoding.DecodeString(rest) // independent stdlib decode
	if err != nil {
		t.Fatalf("independent stdlib decode of the spec's own example failed: %v", err)
	}
	if got := wrapDIDJWK(decoded); got != v.DIDJWKSpecP256DID {
		t.Fatalf("wrapDIDJWK did not reproduce the did:jwk spec's own P-256 example\n got: %s\nwant: %s", got, v.DIDJWKSpecP256DID)
	}
}

// TestUnwrapDIDJWK_MatchesIndependentDecode confirms unwrapDIDJWK, run on the same
// external example, agrees with the Go standard library's own base64url decoder byte for
// byte — the reverse half of the same non-circular check.
func TestUnwrapDIDJWK_MatchesIndependentDecode(t *testing.T) {
	v := loadRFCVectors(t)
	rest := strings.TrimPrefix(v.DIDJWKSpecP256DID, didJWKPrefix)
	want, err := base64.RawURLEncoding.DecodeString(rest)
	if err != nil {
		t.Fatalf("independent stdlib decode failed: %v", err)
	}
	got, err := unwrapDIDJWK(v.DIDJWKSpecP256DID)
	if err != nil {
		t.Fatalf("unwrapDIDJWK: %v", err)
	}
	if string(got) != string(want) {
		t.Fatalf("unwrapDIDJWK disagreed with the independent stdlib decode\n got: %s\nwant: %s", got, want)
	}
}

// TestWrapUnwrap_RoundTrip is the mutation-relevant round-trip: for arbitrary JSON bytes,
// unwrap(wrap(x)) must equal x. A body that always returns a fixed byte slice, or that
// drops/reorders bytes, fails this immediately.
func TestWrapUnwrap_RoundTrip(t *testing.T) {
	cases := [][]byte{
		[]byte(`{"kty":"AKP","alg":"ML-DSA-65","pub":"AAAA"}`),
		[]byte(`{}`),
		[]byte(`x`),
		[]byte(""),
	}
	for _, c := range cases {
		did := wrapDIDJWK(c)
		got, err := unwrapDIDJWK(did)
		if err != nil {
			t.Fatalf("unwrapDIDJWK(wrapDIDJWK(%q)): %v", c, err)
		}
		if string(got) != string(c) {
			t.Fatalf("round trip mismatch: wrapped %q, got back %q", c, got)
		}
	}
}

// TestUnwrapDIDJWK_RejectsBadPrefix is the fail-closed check this package's mutation
// witness targets: a string that does not literally start with "did:jwk:" must be
// rejected with ErrBadDIDPrefix, never silently accepted or treated as if the prefix
// were present.
func TestUnwrapDIDJWK_RejectsBadPrefix(t *testing.T) {
	bad := []string{
		"did:key:eyJhIjoxfQ", // a different DID method
		"jwk:eyJhIjoxfQ",     // missing "did:" entirely
		"DID:JWK:eyJhIjoxfQ", // wrong case — the prefix match is exact
		"",                   // empty string
		"eyJhIjoxfQ",         // no prefix at all
	}
	for _, s := range bad {
		if _, err := unwrapDIDJWK(s); err != ErrBadDIDPrefix {
			t.Fatalf("unwrapDIDJWK(%q): got err=%v, want ErrBadDIDPrefix", s, err)
		}
	}
}

// TestUnwrapDIDJWK_RejectsBadEncoding confirms a well-prefixed but non-base64url
// remainder is rejected with ErrBadDIDEncoding, not silently truncated or ignored.
func TestUnwrapDIDJWK_RejectsBadEncoding(t *testing.T) {
	bad := []string{
		didJWKPrefix + "not valid base64url!!",
		didJWKPrefix + "==padding-should-not-appear==",
		didJWKPrefix + "aGVsbG8=", // padded (RawURLEncoding rejects the '=' padding char)
	}
	for _, s := range bad {
		if _, err := unwrapDIDJWK(s); err != ErrBadDIDEncoding {
			t.Fatalf("unwrapDIDJWK(%q): got err=%v, want ErrBadDIDEncoding", s, err)
		}
	}
}
