# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""Repo-relative path + pinned-corpus helpers for the naalp-bundle test suite. No absolute
paths -- walks upward from this file, mirroring naalp_bundle._bootstrap and
ecosystem/naalp-codec/tests/_paths.py's convention. Every loader here is READ-ONLY: this
package writes nothing outside ecosystem/naalp-bundle/ (the hard scope fence)."""
import json
import os


def _find_repo_root(start):
    d = os.path.abspath(start)
    for _ in range(8):
        if os.path.isfile(os.path.join(d, "vectors", "consume_receipt", "cases.json")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    raise RuntimeError("could not locate the naalp_draft-01 repo root "
                        "(vectors/consume_receipt/cases.json) by walking up from %r" % start)


REPO_ROOT = _find_repo_root(os.path.dirname(os.path.abspath(__file__)))


def load_approval_cases():
    """Independently load vectors/approval/cases.json -- the F3 non-circular oracle for the
    C6 ApprovalRecord body encoding (design.md §7.1), generated from the T4 identity corpus and
    the design's own field layout, sharing no code with impl/python/naalp/approval.py or with
    naalp_bundle. Returns the parsed JSON dict unchanged."""
    path = os.path.join(REPO_ROOT, "vectors", "approval", "cases.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_consume_receipt_cases():
    """Independently load vectors/consume_receipt/cases.json -- the F3 non-circular oracle for
    the T1.5 ledger-signed ConsumeReceipt body encoding (NAALP-REQ-121), generated by
    tools/consume_receipt_oracle.py, a from-scratch model written against design.md §7.5 that
    shares no code with impl/python/naalp/approval.py or with naalp_bundle. Returns the parsed
    JSON dict unchanged."""
    path = os.path.join(REPO_ROOT, "vectors", "consume_receipt", "cases.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_worked_example():
    """Independently load vectors/worked/example.json -- the full byte-level known-answer for a
    complete signed N-AALP object (§2-§4), reference-generated from a fixed seed and reproduced
    identically by impl/go and impl/rust; shares no code with naalp_bundle. Returns the parsed
    JSON dict unchanged."""
    path = os.path.join(REPO_ROOT, "vectors", "worked", "example.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)
