// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.

package envelope

// Object body field numbers (design.md §2.1).
const (
	FieldID       = 1
	FieldKind     = 2
	FieldChannel  = 3
	FieldTier     = 4
	FieldSigner   = 5
	FieldCreated  = 6
	FieldEffect   = 7
	FieldCauses   = 8
	FieldProfile  = 9
	FieldBody     = 10
	FieldExt      = 11
	FieldCext     = 12
	FieldAudience = 13
	FieldSuite    = 14
)

// NaalpVersion is the protected-header naalp-version (design.md §2.5).
const NaalpVersion = 2

// naalpHeaderLabel is the COSE protected-header parameter (RFC 9052 §3.1).
const naalpHeaderLabel = "naalp"

// Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
const (
	MaxObjectSize   = 1048576
	MaxCauses       = 1024
	MaxExt          = 64
	MaxCext         = 64
	MaxNestingDepth = 16
	MaxStreamChunks = 1048576
)
