// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
// Generated by scripts/gen_wire_constants.py from spec/wire-constants.csv. DO NOT EDIT: change the CSV and regenerate. This is the one wire truth projected into this port so ten copies cannot drift.
// Pulled into the envelope module via `include!` (design.md §2.1, §2.5).

// Object body field numbers (design.md §2.1).
pub const FIELD_ID: u64 = 1;
pub const FIELD_KIND: u64 = 2;
pub const FIELD_CHANNEL: u64 = 3;
pub const FIELD_TIER: u64 = 4;
pub const FIELD_SIGNER: u64 = 5;
pub const FIELD_CREATED: u64 = 6;
pub const FIELD_EFFECT: u64 = 7;
pub const FIELD_CAUSES: u64 = 8;
pub const FIELD_PROFILE: u64 = 9;
pub const FIELD_BODY: u64 = 10;
pub const FIELD_EXT: u64 = 11;
pub const FIELD_CEXT: u64 = 12;
pub const FIELD_AUDIENCE: u64 = 13;
pub const FIELD_SUITE: u64 = 14;

// The protected-header naalp-version (design.md §2.5).
pub const NAALP_VERSION: u64 = 2;
const NAALP_HEADER_LABEL: &str = "naalp";

// Decoder bounds (design.md §3.4 (R7)): MUST-level wire limits, projected so ten ports agree.
pub const MAX_OBJECT_SIZE: u64 = 1048576;
pub const MAX_CAUSES: u64 = 1024;
pub const MAX_EXT: u64 = 64;
pub const MAX_CEXT: u64 = 64;
pub const MAX_NESTING_DEPTH: u64 = 16;
pub const MAX_STREAM_CHUNKS: u64 = 1048576;
