# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP `approval.state` conformance oracle (ietf/draft-bubblefish-naalp-01.md "## Approval state
machine" under "# Object State Machines"; impl/go/approval/approval.go ConsumeApproval). Constructs,
from scratch, the F3 non-circular reference for the approval state machine's CONSUME path: every
case's expected {valid, error, ledger_len} outcome is HARDCODED here, read off the draft's normative
table and its two precedence sentences, and carries an inline comment naming the exact row/rule it
encodes. This oracle NEVER imports or calls the approval package -- it does not know the impl exists.

The approval machine (draft "## Approval state machine") has states pending, approved, consumed,
expired, and events approve, consume, expiry. Its table:
    pending  + approve | -> approved
    approved + consume | -> consumed
    approved + expiry  | -> expired
    consumed + consume | reject (AlreadyConsumed)
    expired  + consume | reject (ApprovalExpired)
plus two precedence rules: an args-content-id mismatch is rejected ApprovalMismatch "regardless of
state" and "takes precedence over every cell" (content binding is checked before any state-dependent
reaction); and where an approval is both past not_after AND already consumed, expiry takes precedence
-- a consume is checked against not_after BEFORE the ledger, so it is ApprovalExpired, never
AlreadyConsumed, and the ledger is left untouched. Any (state, event) pair not listed is refused
ApprovalRequired.

What this oracle drives (and does NOT): the "approve" transition (pending -> approved) is the act of
signing an approval object -- it is the setup of every case, not a driven consume verdict, so it is
covered-by-construction, never a graded cell. The "expiry" transition is the passage of not_after,
modelled by a consume whose pos_time > not_after. So the graded surface is the CONSUME path through
the composed choke point ConsumeApproval, whose impl-owned {valid, error} verdict IS the table's
reaction. The oracle deliberately does NOT grade the cell "an approval exists and binds the args but
its granted effect is below the action's required effect": the draft is silent on that cell's error
code (its "# Effects and Authorization" rule names EffectNotAuthorized for effect>grant; its approval
section names ApprovalRequired for a not-granted approval), so hardcoding either verdict would read
it off the impl rather than the draft. Every graded case therefore uses a grant that covers the
required effect (grant=destructive, required=read_only), and the effect-ceiling cell is left to a
future normative-precision decision.

Second graded key -- ledger_len: the draft says a rejected request "leaves [the ledger] untouched".
That is observable as the number of successful consumes recorded (Ledger.Len / len / count across the
ten ports). Grading it catches a mutant that returns the right error Kind but still appends, which the
{valid, error} verdict alone would pass.

Each case builds ONE signed approval (binding the content id `approves_hex`, granting `grant`,
expiring at `not_after`) and drives it through an ordered `events` list of consume attempts on a
fresh single-use ledger; the graded outcome is the LAST event's {valid, error} plus the ledger length
after that last event. present_cid_hex == approves_hex is a match; a different value is an
ApprovalMismatch. pos_time and not_after are kept well below 2^53. Generated by
tools/approval_state_oracle.py; do not hand-edit vectors/approval_state/cases.json.
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Two distinct, valid-SHAPED args content ids (multihash 0x20 0x30 || 48-byte digest). They are
# OPAQUE to the state machine -- ConsumeApproval compares the presented id to the bound id by byte
# equality only -- so their exact bytes are irrelevant; only A != B matters.
CID_A = "2030" + "aa" * 48  # the id the approval binds
CID_B = "2030" + "bb" * 48  # a DIFFERENT presented id -> ApprovalMismatch

NOT_AFTER = 1000  # the approval's expiry (epoch ms; well under 2^53)
T_OK = 500        # a pos_time <= not_after (unexpired)
T_EXPIRED = 2000  # a pos_time > not_after (expired)

GRANT = 3      # destructive: the top of the effect lattice, so it covers every required effect
REQUIRED = 0   # read_only: the required effect of the action being consumed (grant always covers it)


def nonce_hex(tc_id):
    """A stable, distinct anti-replay nonce per case (the machine does not interpret it)."""
    return ("napprove-tc%02d" % tc_id).encode("ascii").hex()


def consume(present_cid_hex, pos_time):
    """One consume attempt: present `present_cid_hex` at `pos_time` for a read_only action."""
    return {"ev": "consume", "present_cid_hex": present_cid_hex, "pos_time": pos_time,
            "required_effect": REQUIRED, "by": "consumer-1"}


def expect(valid, error, ledger_len):
    return {"valid": valid, "error": error, "ledger_len": ledger_len}


def build():
    cases = []

    def add(tc_id, name, table_row, events, expected):
        cases.append({
            "tcId": tc_id,
            "name": name,
            "table_row": table_row,
            "approval": {
                "approves_hex": CID_A,
                "grant": GRANT,
                "not_after": NOT_AFTER,
                "nonce_hex": nonce_hex(tc_id),
                "approver": "approver-1",
            },
            "events": events,
            "expected": expected,
        })

    # approved + consume (match, grant covers required, unexpired, fresh) -> consumed; one append.
    add(1, "approved+consume", "approved | consume | -> consumed",
        [consume(CID_A, T_OK)], expect(True, "", 1))

    # consumed + consume (same id) -> reject AlreadyConsumed; ledger unchanged at 1.
    add(2, "consumed+consume", "consumed | consume | reject (AlreadyConsumed)",
        [consume(CID_A, T_OK), consume(CID_A, T_OK)], expect(False, "AlreadyConsumed", 1))

    # expired + consume -> reject ApprovalExpired; nothing appended (approved -> expiry -> expired,
    # then a consume past not_after).
    add(3, "expired+consume", "expired | consume | reject (ApprovalExpired)",
        [consume(CID_A, T_EXPIRED)], expect(False, "ApprovalExpired", 0))

    # expiry over consumption: a first consume succeeds; a second, now past not_after, is
    # ApprovalExpired (checked before the ledger), NEVER AlreadyConsumed, and the ledger is untouched.
    add(4, "expiry-over-consume",
        "precedence: past not_after AND already consumed -> ApprovalExpired (ledger untouched), never AlreadyConsumed",
        [consume(CID_A, T_OK), consume(CID_A, T_EXPIRED)], expect(False, "ApprovalExpired", 1))

    # ApprovalMismatch, fresh: presented id != bound id -> reject regardless of state; no append.
    add(5, "mismatch-fresh",
        "precedence: args-content-id mismatch -> ApprovalMismatch (over every cell)",
        [consume(CID_B, T_OK)], expect(False, "ApprovalMismatch", 0))

    # ApprovalMismatch over AlreadyConsumed: after a success, a mismatched presentation is
    # ApprovalMismatch (content binding checked before the ledger), not AlreadyConsumed; append stays 1.
    add(6, "mismatch-over-consumed",
        "precedence: mismatch checked before the ledger -> ApprovalMismatch, not AlreadyConsumed",
        [consume(CID_A, T_OK), consume(CID_B, T_OK)], expect(False, "ApprovalMismatch", 1))

    # ApprovalMismatch over ApprovalExpired: a mismatched, also-expired presentation is
    # ApprovalMismatch (content binding checked before expiry); no append.
    add(7, "mismatch-over-expired",
        "precedence: mismatch checked before expiry -> ApprovalMismatch, not ApprovalExpired",
        [consume(CID_B, T_EXPIRED)], expect(False, "ApprovalMismatch", 0))

    # no-state-change-on-rejection: a rejected mismatch leaves the ledger clean, so a subsequent VALID
    # consume still succeeds -> consumed; append becomes 1 (the observable form of "ledger untouched").
    add(8, "reject-then-valid",
        "a rejected request leaves the ledger untouched -> a later valid consume still succeeds",
        [consume(CID_B, T_OK), consume(CID_A, T_OK)], expect(True, "", 1))

    # sequence: success, then mismatch (untouched), then a repeat of the consumed id -> AlreadyConsumed.
    add(9, "success-mismatch-already",
        "consumed | consume | reject (AlreadyConsumed) after an intervening rejected mismatch",
        [consume(CID_A, T_OK), consume(CID_B, T_OK), consume(CID_A, T_OK)],
        expect(False, "AlreadyConsumed", 1))

    return {
        "note": "Independent F3 non-circular oracle for N-AALP approval.state (ietf draft '## Approval "
                "state machine' under '# Object State Machines'). Each case builds one signed approval "
                "and drives it through an ordered `events` list of consume attempts on a fresh single-"
                "use ledger; the graded outcome is the LAST event's {valid, error} plus the ledger "
                "length after it. Expected outcomes are hardcoded here from the draft's normative table "
                "and its mismatch-over-all + expiry-over-consume precedence rules, never computed by "
                "calling the approval package. The effect-ceiling cell (granted effect < required "
                "effect) is deliberately NOT graded -- the draft is silent on its error code. Generated "
                "by tools/approval_state_oracle.py; do not hand-edit.",
        "cases": cases,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "approval_state"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    assert len(data["cases"]) == 9, "expected exactly 9 cases, got %d" % len(data["cases"])
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    for c in data["cases"]:
        print("  tc%02d %-26s -> %s" % (c["tcId"], c["name"], c["expected"]))
    print("wrote", path, "(%d cases)" % len(data["cases"]))


if __name__ == "__main__":
    main()
