# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP `delivery.state` conformance oracle (ietf/draft-bubblefish-naalp-01.md "## Delivery state
machine" under "# Object State Machines"; impl/go/delivery/delivery.go Tracker.Advance). Constructs,
from scratch, the F3 non-circular reference for the delivery state machine: every case's expected
{valid, error, state} outcome is HARDCODED here, read off the draft's normative table, and carries
an inline comment naming the exact table row (or the establish/skip rule) it encodes. This oracle
NEVER imports or calls the Tracker -- it does not know the implementation exists.

The delivery machine (draft # Delivery, # Object State Machines) has four monotonic stages,
persisted_origin (0) -> accepted_relay (1) -> persisted_target (2) -> presented (3). Its one event
is a delivery update reporting a stage S'. Relative to the machine's current state -- the highest
stage already reached for the object -- the update is classified advance(S') when S' > current,
repeat(S') when S' == current, and regress(S') when S' < current. advance(S') transitions directly
to S' (a stage MAY be skipped -- skipping is not a regression); repeat is an idempotent no-op
leaving the state unchanged; regress is rejected StageOutOfOrder with no state change. Before any
update the object is unseen (no "highest stage already reached"), so the first update establishes
the state at the stage it reports with no error -- there is nothing below it to regress against
(draft # Delivery: "A stage earlier than the one already reached is rejected"; nothing is already
reached before the first update). Any (state, event) pair not listed in the table is rejected
StageOutOfOrder; because advance/repeat/regress partition every in-range S' relative to the current
stage, the listed rows are total over the four stages.

Table rows encoded (draft "## Delivery state machine"):
  <unseen>          + update(S')            -> S'                (establish; first update, no regress possible)
  persisted_origin  + advance(S')           -> S'                (incl. legal skip to persisted_target/presented)
  persisted_origin  + repeat(0)             -> persisted_origin
  accepted_relay    + advance(S')           -> S'                (incl. legal skip to presented)
  accepted_relay    + repeat(1)             -> accepted_relay
  accepted_relay    + regress(S')           -> reject StageOutOfOrder (stays accepted_relay)
  persisted_target  + advance(S')           -> presented         (S'>2 => S'=3=presented)
  persisted_target  + repeat(2)             -> persisted_target
  persisted_target  + regress(S')           -> reject StageOutOfOrder (stays persisted_target)
  presented         + repeat(3)             -> presented
  presented         + regress(S')           -> reject StageOutOfOrder (stays presented)
  any other unlisted (state, event) pair    -> reject StageOutOfOrder

Each case drives ONE object through an ordered `events` list on a fresh delivery tracker; the graded
outcome is the LAST event's {valid, error} plus the object's final stage name after that last event.
A rejected event never changes the recorded stage. Generated by tools/delivery_state_oracle.py; do
not hand-edit vectors/delivery_state/cases.json.
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Stage values + names (delivery.go StagePersistedOrigin..StagePresented / stageNames).
PERSISTED_ORIGIN = 0
ACCEPTED_RELAY = 1
PERSISTED_TARGET = 2
PRESENTED = 3
STAGE_NAME = {0: "persisted_origin", 1: "accepted_relay", 2: "persisted_target", 3: "presented"}


def obj_id_hex(tc_id):
    """A stable, distinct object content id per test case (any hex; the oracle only needs it stable)."""
    return ("delivery-tc%02d" % tc_id).encode("ascii").hex()


def ev_update(obj_hex, stage):
    """One signed delivery.update reporting `stage` for `obj_hex` (delivery.go DeliveryUpdate)."""
    return {"ev": "update", "obj_hex": obj_hex, "stage": stage}


def expect(valid, error, state):
    return {"valid": valid, "error": error, "state": state}


def build():
    cases = []

    def add(tc_id, name, table_row, events, expected):
        cases.append({
            "tcId": tc_id,
            "name": name,
            "table_row": table_row,
            "events": events,
            "expected": expected,
        })

    # Trace prefixes that drive a fresh object UP to a given from-state. The first update establishes
    # (unseen -> the reported stage, no regress possible); a later strictly-greater update advances
    # (a skip is legal). These prefixes are themselves all-valid; the graded event is the one appended.
    def to_origin(o):
        return [ev_update(o, PERSISTED_ORIGIN)]                       # establish at persisted_origin

    def to_relay(o):
        return [ev_update(o, PERSISTED_ORIGIN), ev_update(o, ACCEPTED_RELAY)]

    def to_target(o):
        # establish origin, then advance-with-skip to persisted_target (legal skip of accepted_relay)
        return [ev_update(o, PERSISTED_ORIGIN), ev_update(o, PERSISTED_TARGET)]

    def to_presented(o):
        return [ev_update(o, PERSISTED_ORIGIN), ev_update(o, PRESENTED)]

    # --- establish (first update; unseen -> S') ---
    o = obj_id_hex(1)
    add(1, "establish-origin", "<unseen> | update(0) | -> persisted_origin [establish, first update]",
        to_origin(o), expect(True, "", "persisted_origin"))

    o = obj_id_hex(2)
    add(2, "establish-skip-to-target",
        "<unseen> | update(2) | -> persisted_target [establish; first update may report any stage]",
        [ev_update(o, PERSISTED_TARGET)], expect(True, "", "persisted_target"))

    # --- from persisted_origin ---
    o = obj_id_hex(3)
    add(3, "origin+advance-relay", "persisted_origin | advance(1) | -> accepted_relay",
        to_origin(o) + [ev_update(o, ACCEPTED_RELAY)], expect(True, "", "accepted_relay"))

    o = obj_id_hex(4)
    add(4, "origin+advance-skip-target", "persisted_origin | advance(2) | -> persisted_target [legal skip]",
        to_origin(o) + [ev_update(o, PERSISTED_TARGET)], expect(True, "", "persisted_target"))

    o = obj_id_hex(5)
    add(5, "origin+advance-skip-presented", "persisted_origin | advance(3) | -> presented [legal skip]",
        to_origin(o) + [ev_update(o, PRESENTED)], expect(True, "", "presented"))

    o = obj_id_hex(6)
    add(6, "origin+repeat", "persisted_origin | repeat(0) | -> persisted_origin [idempotent]",
        to_origin(o) + [ev_update(o, PERSISTED_ORIGIN)], expect(True, "", "persisted_origin"))

    # --- from accepted_relay ---
    o = obj_id_hex(7)
    add(7, "relay+advance-target", "accepted_relay | advance(2) | -> persisted_target",
        to_relay(o) + [ev_update(o, PERSISTED_TARGET)], expect(True, "", "persisted_target"))

    o = obj_id_hex(8)
    add(8, "relay+advance-skip-presented", "accepted_relay | advance(3) | -> presented [legal skip]",
        to_relay(o) + [ev_update(o, PRESENTED)], expect(True, "", "presented"))

    o = obj_id_hex(9)
    add(9, "relay+repeat", "accepted_relay | repeat(1) | -> accepted_relay [idempotent]",
        to_relay(o) + [ev_update(o, ACCEPTED_RELAY)], expect(True, "", "accepted_relay"))

    o = obj_id_hex(10)
    add(10, "relay+regress", "accepted_relay | regress(0) | reject (StageOutOfOrder) [stays accepted_relay]",
        to_relay(o) + [ev_update(o, PERSISTED_ORIGIN)], expect(False, "StageOutOfOrder", "accepted_relay"))

    # --- from persisted_target ---
    o = obj_id_hex(11)
    add(11, "target+advance-presented", "persisted_target | advance(3) | -> presented",
        to_target(o) + [ev_update(o, PRESENTED)], expect(True, "", "presented"))

    o = obj_id_hex(12)
    add(12, "target+repeat", "persisted_target | repeat(2) | -> persisted_target [idempotent]",
        to_target(o) + [ev_update(o, PERSISTED_TARGET)], expect(True, "", "persisted_target"))

    o = obj_id_hex(13)
    add(13, "target+regress-relay", "persisted_target | regress(1) | reject (StageOutOfOrder) [stays persisted_target]",
        to_target(o) + [ev_update(o, ACCEPTED_RELAY)], expect(False, "StageOutOfOrder", "persisted_target"))

    o = obj_id_hex(14)
    add(14, "target+regress-origin", "persisted_target | regress(0) | reject (StageOutOfOrder) [stays persisted_target]",
        to_target(o) + [ev_update(o, PERSISTED_ORIGIN)], expect(False, "StageOutOfOrder", "persisted_target"))

    # --- from presented (terminal top: no advance possible) ---
    o = obj_id_hex(15)
    add(15, "presented+repeat", "presented | repeat(3) | -> presented [idempotent]",
        to_presented(o) + [ev_update(o, PRESENTED)], expect(True, "", "presented"))

    o = obj_id_hex(16)
    add(16, "presented+regress-target", "presented | regress(2) | reject (StageOutOfOrder) [stays presented]",
        to_presented(o) + [ev_update(o, PERSISTED_TARGET)], expect(False, "StageOutOfOrder", "presented"))

    o = obj_id_hex(17)
    add(17, "presented+regress-relay", "presented | regress(1) | reject (StageOutOfOrder) [stays presented]",
        to_presented(o) + [ev_update(o, ACCEPTED_RELAY)], expect(False, "StageOutOfOrder", "presented"))

    o = obj_id_hex(18)
    add(18, "presented+regress-origin", "presented | regress(0) | reject (StageOutOfOrder) [stays presented]",
        to_presented(o) + [ev_update(o, PERSISTED_ORIGIN)], expect(False, "StageOutOfOrder", "presented"))

    return {
        "note": "Independent F3 non-circular oracle for N-AALP delivery.state (ietf draft '## Delivery "
                "state machine' under '# Object State Machines'). Every case drives one object through "
                "an ordered `events` list of signed delivery updates on a fresh tracker; the graded "
                "outcome is the LAST event's {valid, error} plus the object's final stage name. Expected "
                "outcomes are hardcoded here from the draft's normative table, never computed by calling "
                "delivery.Tracker. Generated by tools/delivery_state_oracle.py; do not hand-edit.",
        "stage_names": STAGE_NAME,
        "cases": cases,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "delivery_state"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    assert len(data["cases"]) == 18, "expected exactly 18 cases, got %d" % len(data["cases"])
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    for c in data["cases"]:
        print("  tc%02d %-28s -> %s" % (c["tcId"], c["name"], c["expected"]))
    print("wrote", path, "(%d cases)" % len(data["cases"]))


if __name__ == "__main__":
    main()
