# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP §3.1.1 determinism-disposition oracle (design.md §3.1.1, R5). Constructs, from scratch
over the shared deterministic-CBOR encoder (cbor_oracle.py, RFC 8949) and independent of impl/go
and impl/rust, the MUST-REJECT byte authority for the RFC 8949 §4.2.2 / RFC 9052 §3 dispositions:

  - a CBOR float (major type 7) in the object body, in ext, or in cext -> NonCanonical
  - a duplicate map key inside ext                                       -> NonCanonical
  - the 0x41A0 (bstr-wrapped empty map) encoding of an empty protected
    header, instead of the pinned 0x40                                   -> NonCanonical

Every reject vector is an OTHERWISE-VALID worked object (a tag-18 COSE_Sign1) carrying exactly one
determinism violation, so the only reason a conforming decoder rejects it is the disposition under
test. Each reject is reached at the parse/decode stage — the body decode for a float or duplicate
key, the protected-header parse for 0x41A0 — BEFORE the content-id or signature is checked
(design.md D10: an untrusted object is decoded before it is authenticated), so the vectors carry a
deliberately garbage signature and, for the float/dup-key cases, a placeholder content-id (never
reached). The 0x41A0 vector's body is fully canonical, so it carries a real content-id; only its
protected header is malformed.

Floats and duplicate keys cannot be produced by the strict encoder (the spine has no floats;
encode() rejects duplicate keys), so they are injected with the ("raw", <bytes>) escape the shared
encoder exposes for exactly this must-reject-oracle purpose — legitimately non-circular, F3.

Generated by tools/determinism_oracle.py; do not hand-edit.
"""
import hashlib
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cbor_oracle  # shared deterministic-CBOR encoder (+ the ("raw", bytes) escape)

enc = cbor_oracle.encode

ALG_MLDSA65 = -49
VERSION = 2  # draft-01 wire revision (design.md §2.5.3)
SIGNER = bytes.fromhex("5349474e45525f41")  # "SIGNER_A"
PROFILE = 1
GARBAGE_SIG = b"\x00" * 8  # deliberately invalid: every reject fires before the signature is checked

# A CBOR float16 = 1.5 (major type 7). No N-AALP field is ever a float (§3.1.1); its presence is
# the whole reason the decoder rejects, so the exact float value is immaterial.
FLOAT_HALF = ("raw", bytes.fromhex("f93e00"))
# A raw CBOR map {100:1, 100:2} — two entries with the SAME key. encode() would refuse to build
# this (it rejects duplicate keys), so it is injected verbatim; the decoder rejects it on the
# duplicate key (RFC 8949 §5.6).
DUPKEY_MAP = ("raw", bytes.fromhex("a2186401186402"))
# A valid-shaped multihash (sha2-384 code 0x20, length 0x30) with a zero digest: the content-id
# field for the float/dup-key vectors, which are rejected during body decode before the id is ever
# recomputed, so its digest is immaterial.
PLACEHOLDER_ID = b"\x20\x30" + b"\x00" * 48


def naalp_protected():
    """The C3 object protected header {1: alg, "naalp": {1:signer, 2:profile, 3:version}}."""
    return enc(("map", [(1, ALG_MLDSA65),
                        ("naalp", ("map", [(1, SIGNER), (2, PROFILE), (3, VERSION)]))]))


def base_body_fields():
    """An otherwise-valid worked-object body (fields 2..10, ascending), no violation injected:
    kind=2, channel=4, tier=0, signer=SIGNER_A, created, effect=2, causes=[], profile=1,
    body='hello'. Field 1 (id) is supplied by the caller (a real id or the placeholder)."""
    return [
        (2, 2), (3, 4), (4, 0), (5, SIGNER), (6, 1785000000000),
        (7, 2), (8, []), (9, PROFILE), (10, "hello"),
    ]


def with_field(fields, key, value):
    """Return fields with `key` set to `value`, preserving ascending key order."""
    out = [(k, v) for (k, v) in fields if k != key]
    out.append((key, value))
    out.sort(key=lambda p: p[0])
    return out


def real_content_id(body_no_id_pairs):
    """multihash(0x20, SHA-384(canonical body without field 1)) — only meaningful for a body with
    no injected non-canonical item (the 0x41A0 vector)."""
    return b"\x20\x30" + hashlib.sha384(enc(("map", body_no_id_pairs))).digest()


def cose_sign1(body_with_id_pairs, protected_bytes):
    """Wrap a full body (list of (k,v) INCLUDING field 1) in a tag-18 COSE_Sign1 with the given
    serialized protected header (as raw bytes) and a garbage signature. protected_bytes and the
    serialized payload are passed as `bytes`, so the shared encoder wraps EACH as a COSE bstr
    (major 2) — matching tag-18 [protected:bstr, unprotected, payload:bstr, signature:bstr]. For
    the 0x41A0 vector protected_bytes is the single byte 0xA0, so the element is the wire bytes
    41 A0 (a 1-byte bstr wrapping an empty map)."""
    payload = enc(("map", body_with_id_pairs))
    obj = enc(("tag", 18, [protected_bytes, ("map", []), payload, GARBAGE_SIG]))
    return obj


def build():
    reject = []

    # --- float in the body (field 10) -----------------------------------------------------------
    fb = with_field(base_body_fields(), 10, FLOAT_HALF)
    body = [(1, PLACEHOLDER_ID)] + fb
    obj = cose_sign1(body, naalp_protected())
    reject.append({"name": "float_body", "obj_hex": obj.hex(), "error": "NonCanonical",
                   "note": "body field 10 is a CBOR float (major 7); forbidden (§3.1.1, R5)"})

    # --- float in ext (field 11 value) ----------------------------------------------------------
    fe = with_field(base_body_fields(), 11, ("map", [(100, FLOAT_HALF)]))
    body = [(1, PLACEHOLDER_ID)] + fe
    obj = cose_sign1(body, naalp_protected())
    reject.append({"name": "float_ext", "obj_hex": obj.hex(), "error": "NonCanonical",
                   "note": "ext (field 11) key 100 value is a CBOR float; forbidden (§3.1.1, R5)"})

    # --- float in cext (field 12 value) ---------------------------------------------------------
    fc = with_field(base_body_fields(), 12, ("map", [(100, FLOAT_HALF)]))
    body = [(1, PLACEHOLDER_ID)] + fc
    obj = cose_sign1(body, naalp_protected())
    reject.append({"name": "float_cext", "obj_hex": obj.hex(), "error": "NonCanonical",
                   "note": "cext (field 12) key 100 value is a CBOR float; forbidden (§3.1.1, R5)"})

    # --- duplicate map key inside ext (field 11) ------------------------------------------------
    de = with_field(base_body_fields(), 11, DUPKEY_MAP)
    body = [(1, PLACEHOLDER_ID)] + de
    obj = cose_sign1(body, naalp_protected())
    reject.append({"name": "dupkey_ext", "obj_hex": obj.hex(), "error": "NonCanonical",
                   "note": "ext (field 11) is a map with two identical keys (RFC 8949 §5.6, §3.1.1)"})

    # --- empty protected header encoded as 0x41A0 instead of 0x40 --------------------------------
    # Body is fully canonical here (only the header is malformed), so it carries a real content-id.
    vb = base_body_fields()
    body = [(1, real_content_id(vb))] + vb
    # protected header element = a bstr wrapping an empty map: the 0x41A0 wire form. cose_sign1
    # serializes the protected argument as a bstr, so passing the empty-map bytes (0xA0) yields
    # the 0x41A0 element (a 1-byte bstr whose content is 0xA0).
    obj = cose_sign1(body, bytes.fromhex("a0"))
    reject.append({"name": "protected_0x41a0", "obj_hex": obj.hex(), "error": "NonCanonical",
                   "note": "empty protected header encoded 0x41A0 (bstr-wrapped empty map) not 0x40 (§3.1.1, R5)"})

    # --- structural self-check (NOT a corpus case) ----------------------------------------------
    # The base body with NO violation MUST encode canonically (encode() would raise on a duplicate
    # key and cannot emit a float), and its content-id must be a well-formed 50-byte multihash.
    clean = base_body_fields()
    enc(("map", [(1, real_content_id(clean))] + clean))  # raises if the clean base is non-canonical
    cid = real_content_id(clean)
    assert len(cid) == 50 and cid[:2] == b"\x20\x30", "clean base content-id malformed"
    # And the empty-map bytes 0xA0, passed as `bytes`, really encode to the 0x41A0 wire element.
    assert enc(bytes.fromhex("a0")) == b"\x41\xa0", "0x41A0 wire form self-check failed"

    return {
        "note": "Independent oracle output for the N-AALP §3.1.1 determinism dispositions (float "
                "forbid, 0x40 empty-header pin / 0x41A0 reject, duplicate-key reject). Every port "
                "MUST reject each object.decode vector with the exact named error. Generated by "
                "tools/determinism_oracle.py; do not hand-edit.",
        "object_decode_reject": reject,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "determinism"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    for r in data["object_decode_reject"]:
        print("  reject", r["name"], "->", r["error"], "obj", len(r["obj_hex"]) // 2, "bytes")
    print("wrote", path)


if __name__ == "__main__":
    main()
