# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP C3 independent oracle: the full object envelope (design.md §2). Constructs, from
scratch over the shared deterministic-CBOR encoder (cbor_oracle.py, RFC 8949), the byte
authority for a worked object: the body map (fields 1..12), the content id
multihash(0x20, SHA-384(canonical-body-without-field-1)) (§2.3), the COSE_Sign1 payload,
the enriched protected header {1: alg, "naalp": {1:signer, 2:profile, 3:version}} (§2.1,
§2.5), and the COSE_Sign1 ToBeSigned (RFC 9052 §4.4). Go and Rust must reproduce every
*_hex. The ML-DSA signature is not emitted here (see cose_oracle.py); the signed object's
sign/verify and the two-implementation byte-parity are graded in the impl suites.
"""
import hashlib
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cbor_oracle  # shared deterministic-CBOR encoder (Nint/Tag/tstr-key aware)

enc = cbor_oracle.encode

VERSION = 1
ALG_MLDSA65 = -49


def content_id(body_no_id_pairs):
    digest = hashlib.sha384(enc(("map", body_no_id_pairs))).digest()  # 48 bytes
    return b"\x20\x30" + digest


def build():
    signer = bytes.fromhex("5349474e45525f41")  # "SIGNER_A" (opaque bstr; real id is C4/T4)
    kind, channel, tier, created, effect, profile = 2, 4, 0, 1785000000000, 2, 1
    body_str = "hello"

    # Body without field 1 (id), fields in ascending key order.
    body_no_id = [
        (2, kind), (3, channel), (4, tier), (5, signer), (6, created),
        (7, effect), (8, []), (9, profile), (10, body_str),
    ]
    body_no_id_hex = enc(("map", body_no_id)).hex()
    cid = content_id(body_no_id)

    full = [(1, cid)] + body_no_id
    payload = enc(("map", full))

    naalp = ("map", [(1, signer), (2, profile), (3, VERSION)])
    protected = enc(("map", [(1, ALG_MLDSA65), ("naalp", naalp)]))

    tbs = enc(["Signature1", protected, b"", payload])

    return {
        "note": "Independent oracle output for N-AALP C3 (object envelope). Go and Rust MUST "
                "reproduce content_id_hex, payload_hex, protected_hex, and tobesigned_hex for the "
                "worked object, then sign/verify it offline and reject every §2.6 failure mode. "
                "Generated by tools/envelope_oracle.py; do not hand-edit.",
        "object": {
            "kind": kind, "channel": channel, "tier": tier,
            "signer_hex": signer.hex(), "created": created, "effect": effect,
            "causes_hex": [], "profile": profile, "body_str": body_str,
            "alg": ALG_MLDSA65, "version": VERSION,
            "body_no_id_hex": body_no_id_hex,
            "content_id_hex": cid.hex(),
            "payload_hex": payload.hex(),
            "protected_hex": protected.hex(),
            "tobesigned_hex": tbs.hex(),
        },
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "envelope"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    o = data["object"]
    print("content-id", o["content_id_hex"][:20], "...")
    print("payload", len(o["payload_hex"]) // 2, "bytes; protected", len(o["protected_hex"]) // 2,
          "bytes; tobesigned", len(o["tobesigned_hex"]) // 2, "bytes")
    print("wrote", path)


if __name__ == "__main__":
    main()
