# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP R7 decoder-resource-bounds oracle (design.md §3.4). Constructs, from scratch over the
shared deterministic-CBOR encoder (cbor_oracle.py, RFC 8949) and independent of impl/go and
impl/rust, the MUST-REJECT byte authority for the six R7 bounds. Every reject vector is an
OTHERWISE-VALID worked object (a tag-18 COSE_Sign1 over a real body with a correct content-id)
pushed EXACTLY ONE dimension one-past-limit, so the only reason a conforming decoder rejects it
is the bound under test. All four object-level bounds fire before the COSE signature is checked
(design.md D10: "an untrusted object is decoded before it is authenticated"), so the vectors
carry a deliberately garbage signature — the reject is reached with no crypto.

The six bounds and their named errors (spec/wire-constants.csv, the CSV authority this oracle
PARSES rather than hardcodes):
  - object octet size   > MAX_OBJECT_SIZE   -> TooLarge          (raw length, before any parse)
  - CBOR nesting depth  > MAX_NESTING_DEPTH -> DepthExceeded      (outermost item = depth 1)
  - |causes| (field 8)  > MAX_CAUSES        -> TooManyCauses
  - |ext|    (field 11) > MAX_EXT           -> TooManyExtensions
  - |cext|   (field 12) > MAX_CEXT          -> TooManyExtensions
  - stream chunk count  > MAX_STREAM_CHUNKS -> TooManyChunks      (streaming layer, not object.decode)

TooLarge and TooManyChunks are size/count-infeasible as literal corpus bytes (a >1 MiB object is
~6x the whole corpus; 2^20 chunks is not a literal at all), so they are carried PARAMETERIZED:
the corpus fixes the over-limit size/count and the named error, and each port's adapter
materializes the padding locally. What is oracle-fixed for those two is the length/count + the
Kind, which is exactly the property under test (the byte content of padding is irrelevant to a
length/count check) — legitimately non-circular, F3-compliant.

Reject-only by design: the task deliverable is the reject vector (tasks.md T7.1). Accept-at-limit
is already unit-tested per port with real signing; here the oracle instead STRUCTURALLY self-checks
that its own at-limit sibling (exactly at the limit) does NOT trip the bound, catching an off-by-one
without shipping a signature. Generated by tools/envelope_bounds_oracle.py; do not hand-edit.
"""
import csv
import hashlib
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cbor_oracle  # shared deterministic-CBOR encoder

enc = cbor_oracle.encode

ALG_MLDSA65 = -49
VERSION = 2  # draft-01 wire revision (design.md §2.5.3)
GARBAGE_SIG = b"\x00" * 8  # deliberately invalid: every bound fires before VerifyRaw


def read_bounds():
    """Parse the six MUST-level maxima from spec/wire-constants.csv (the CSV authority).

    Row shape: '<bare name>,<value>,<type>,<coverage>,<PascalName;MACRO_NAME>'. We key on the
    bare name so a value change in the CSV flows here without a code edit (drift-proof)."""
    path = os.path.normpath(os.path.join(HERE, "..", "spec", "wire-constants.csv"))
    want = {
        "max object octet size": "MAX_OBJECT_SIZE",
        "max causes count": "MAX_CAUSES",
        "max ext count": "MAX_EXT",
        "max cext count": "MAX_CEXT",
        "max nesting depth": "MAX_NESTING_DEPTH",
        "max stream chunks": "MAX_STREAM_CHUNKS",
    }
    out = {}
    with io.open(path, "r", encoding="utf-8") as f:
        for row in csv.reader(f):
            if not row or len(row) < 2:
                continue
            name = row[0].strip()
            if name in want:
                out[want[name]] = int(row[1].strip())
    missing = [v for v in want.values() if v not in out]
    if missing:
        raise SystemExit("wire-constants.csv missing bounds: %s" % missing)
    return out


# ---- object construction (mirrors tools/envelope_oracle.py's worked object) -------

def content_id(body_no_id_pairs):
    return b"\x20\x30" + hashlib.sha384(enc(("map", body_no_id_pairs))).digest()


def cose_sign1(body_no_id_pairs):
    """Wrap a body (list of (k,v) without field 1) as a full tag-18 COSE_Sign1 object with a
    correct content-id and a garbage signature. Returns the object bytes (what Verify receives)."""
    cid = content_id(body_no_id_pairs)
    payload = enc(("map", [(1, cid)] + body_no_id_pairs))
    protected = enc(("map", [(1, ALG_MLDSA65),
                             ("naalp", ("map", [(1, SIGNER), (2, PROFILE), (3, VERSION)]))]))
    obj = enc(("tag", 18, [protected, ("map", []), payload, GARBAGE_SIG]))
    return obj, cid


SIGNER = bytes.fromhex("5349474e45525f41")  # "SIGNER_A"
PROFILE = 1


def base_fields():
    """An otherwise-valid worked-object body (fields 2..12, ascending), no bound tripped.
    kind=2, channel=4, tier=0, effect=2, causes=[], profile=1, body='hello'."""
    return [
        (2, 2), (3, 4), (4, 0), (5, SIGNER), (6, 1785000000000),
        (7, 2), (8, []), (9, PROFILE), (10, "hello"),
    ]


def with_field(fields, key, value):
    """Return fields with `key` set to `value`, preserving ascending key order."""
    out = [(k, v) for (k, v) in fields if k != key]
    out.append((key, value))
    out.sort(key=lambda p: p[0])
    return out


def nest_arrays(n):
    """n nested arrays wrapping a 0 scalar: n=0 -> 0; n=1 -> [0]; n=2 -> [[0]] ..."""
    v = 0
    for _ in range(n):
        v = [v]
    return v


def measured_depth(v, depth=1):
    """Max CBOR item depth as the decoder counts it: the item HERE is at `depth`; a container's
    elements are at depth+1 (outermost item = depth 1). Mirrors impl decode(depth) recursion."""
    if isinstance(v, list):
        return max([depth] + [measured_depth(x, depth + 1) for x in v])
    if isinstance(v, tuple) and v and v[0] == "map":
        d = depth
        for (k, val) in v[1]:
            d = max(d, measured_depth(k, depth + 1), measured_depth(val, depth + 1))
        return d
    return depth


def build():
    B = read_bounds()
    base = base_fields()

    # --- object.decode reject vectors (obj_hex + named Kind), one dimension one-past-limit ---
    reject = []

    # DepthExceeded: field 10 = a value nested so its deepest item sits at MAX_NESTING_DEPTH+1.
    # The payload map is depth 1; field 10's value starts at depth 2. n nested arrays put the
    # innermost array at depth (1 + 1 + (n-1)) = n+1, so n = MAX_NESTING_DEPTH gives depth+1.
    # field-10 value starts at depth 2 (inside the payload map at depth 1); nest_arrays(n) puts its
    # deepest item (the scalar) at depth 2+n, so n = MAX-1 lands the scalar at MAX+1 (one past), and
    # n = MAX-2 lands it exactly at MAX (the at-limit sibling).
    depth = B["MAX_NESTING_DEPTH"]
    over_deep = with_field(base, 10, nest_arrays(depth - 1))        # deepest item at depth MAX+1
    at_deep = with_field(base, 10, nest_arrays(depth - 2))          # deepest item at depth MAX
    over_payload = ("map", [(1, content_id(over_deep))] + over_deep)
    at_payload = ("map", [(1, content_id(at_deep))] + at_deep)
    md_over = measured_depth(over_payload)
    md_at = measured_depth(at_payload)
    assert md_over == B["MAX_NESTING_DEPTH"] + 1, "over-deep must be MAX+1, got %d" % md_over
    assert md_at == B["MAX_NESTING_DEPTH"], "at-limit must be exactly MAX, got %d" % md_at
    obj, _ = cose_sign1(over_deep)
    reject.append({"name": "depth_over", "obj_hex": obj.hex(), "error": "DepthExceeded",
                   "note": "payload item at depth %d > MAX_NESTING_DEPTH %d" % (md_over, B["MAX_NESTING_DEPTH"])})

    # TooManyCauses: field 8 = MAX_CAUSES+1 minimal causes (empty bstrs; the cardinality check
    # fires on len before any per-cause validation).
    over_causes = with_field(base, 8, [b""] * (B["MAX_CAUSES"] + 1))
    assert len([v for v in over_causes if v[0] == 8][0][1]) == B["MAX_CAUSES"] + 1
    obj, _ = cose_sign1(over_causes)
    reject.append({"name": "causes_over", "obj_hex": obj.hex(), "error": "TooManyCauses",
                   "note": "|causes| = %d > MAX_CAUSES %d" % (B["MAX_CAUSES"] + 1, B["MAX_CAUSES"])})

    # TooManyExtensions (ext, field 11): MAX_EXT+1 distinct int-keyed entries; cext absent.
    over_ext = with_field(base, 11, ("map", [(i, 0) for i in range(1, B["MAX_EXT"] + 2)]))
    obj, _ = cose_sign1(over_ext)
    reject.append({"name": "ext_over", "obj_hex": obj.hex(), "error": "TooManyExtensions",
                   "note": "|ext| = %d > MAX_EXT %d (field 11 only over-limit)" % (B["MAX_EXT"] + 1, B["MAX_EXT"])})

    # TooManyExtensions (cext, field 12): MAX_CEXT+1 distinct int-keyed entries; ext absent.
    over_cext = with_field(base, 12, ("map", [(i, 0) for i in range(1, B["MAX_CEXT"] + 2)]))
    obj, _ = cose_sign1(over_cext)
    reject.append({"name": "cext_over", "obj_hex": obj.hex(), "error": "TooManyExtensions",
                   "note": "|cext| = %d > MAX_CEXT %d (field 12 only over-limit)" % (B["MAX_CEXT"] + 1, B["MAX_CEXT"])})

    # at-limit structural self-checks (NOT corpus cases): exactly at the limit must not be over.
    at_causes = with_field(base, 8, [b""] * B["MAX_CAUSES"])
    at_ext = with_field(base, 11, ("map", [(i, 0) for i in range(1, B["MAX_EXT"] + 1)]))
    at_cext = with_field(base, 12, ("map", [(i, 0) for i in range(1, B["MAX_CEXT"] + 1)]))
    assert len([v for v in at_causes if v[0] == 8][0][1]) == B["MAX_CAUSES"]
    assert len([v for v in at_ext if v[0] == 11][0][1][1]) == B["MAX_EXT"]
    assert len([v for v in at_cext if v[0] == 12][0][1][1]) == B["MAX_CEXT"]

    return {
        "note": "Independent oracle output for N-AALP R7 decoder resource bounds (design.md §3.4). "
                "Every port MUST reject each object.decode vector with the exact named error, and "
                "reject the size/count-parameterized cases (which each port's adapter materializes). "
                "Generated by tools/envelope_bounds_oracle.py; do not hand-edit.",
        "bounds": B,
        "object_decode_reject": reject,
        "size_parameterized": [
            {"name": "size_over", "op": "object.decode", "over_size": B["MAX_OBJECT_SIZE"] + 1,
             "error": "TooLarge",
             "note": "adapter passes MAX_OBJECT_SIZE+1 raw bytes to verify; rejected on length before parse"},
        ],
        "chunk_parameterized": [
            {"name": "chunks_over", "op": "stream.commit", "chunk_count": B["MAX_STREAM_CHUNKS"] + 1,
             "error": "TooManyChunks",
             "note": "adapter materializes MAX_STREAM_CHUNKS+1 empty chunks + a matching commit; "
                     "count check fires before the digest check"},
        ],
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "envelope_bounds"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    print("bounds:", data["bounds"])
    for r in data["object_decode_reject"]:
        print("  reject", r["name"], "->", r["error"], "obj", len(r["obj_hex"]) // 2, "bytes")
    for r in data["size_parameterized"] + data["chunk_parameterized"]:
        print("  param ", r["name"], "->", r["error"])
    print("wrote", path)


if __name__ == "__main__":
    main()
