# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP Error Code registry + naalp-error object oracle (design.md §3.5, R3.3/R3.4, T3.3).

This is the independent byte + taxonomy authority for the "N-AALP Error Codes" registry and the
`naalp-error` object body carried on the Control/Error surface (channel 0x0000, kind 3). It shares
no code with impl/go or impl/rust; Go, Rust, and the eight other ports are graded by reproducing
the bytes and the name<->code mapping this file emits (non-circular, F3 / CLAUDE.md).

WHAT IS REGISTERED (scope discriminator, advisor-ruled 2026-08-23): every protocol error the
specification defines as a fail-closed rejection reason returnable by a verify/decode path on
peer-supplied input -- the spine AND all twenty channel surfaces. EXCLUDED are purely local errors
never carried to a peer: the encoder-side `Unencodable`, and the key-generation input errors
`SeedSize` / `KeyMalformed`. `Malformed` is the generic fallback. `FlowControlError` is a
transport-binding property, not an N-AALP object rejection, and is not registered.

CODE ASSIGNMENT (fields of record): codes are assigned sequentially from 1 in the documented
subsystem order below (spine first, then the channel surfaces in build order); 0 is reserved and
MUST NOT appear on the wire. The standards range is 1..0x7FFF (RFC Required / FCFS, ISE-permissible
per the runbook); >=0x8000 is private-use, no registration. The order -- not any per-error choice
-- is the named source for every code, so the scheme is reproducible.

RETRYABLE (fields of record): true iff an unmodified retry of the same object can later succeed
because of a transient/environmental change with no object or configuration change. Every
deterministic verification/decode failure is therefore non-retryable (retrying identical bytes
fails identically -- the fail-closed default); the only registered transient is `NotDelivered`
(a carriage delivery that did not complete may complete on a later attempt).

DUAL-CARRIAGE RULES (design.md §3.5, graded by the reject/opaque cases below):
  * a naalp-error whose `code` (field 1) is registered MUST carry the registered `name` (field 2);
    a code/name disagreement is rejected `Malformed` (the strengthening direction).
  * a `code` outside the receiver's registry snapshot MUST NOT be fatal: the registry is open
    (RFC Required), so the error is treated as opaque -- the name is diagnostic only and no
    semantics are inferred -- for forward compatibility with a later-registered code.

Generated by tools/error_codes_oracle.py; do not hand-edit the emitted files.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cbor_oracle  # shared deterministic-CBOR encoder (RFC 8949 §4.2.1)

enc = cbor_oracle.encode
ROOT = os.path.join(HERE, "..")

# ---- the canonical ordered error set (name, retryable, subsystem, description) --------------
# Order IS the code assignment: code = index + 1. Do not reorder without re-pinning every vector.
CANON = [
    # encoding / CBOR (§3.1)
    ("NonCanonical", False, "encoding", "object or header is not the deterministic RFC 8949 §4.2.1 encoding (non-minimal, indefinite-length, unsorted or duplicate keys, a float, or the 0x41A0 empty header)"),
    ("DepthExceeded", False, "encoding", "CBOR nesting depth exceeds the maximum (§3.4)"),
    # object / envelope (§3)
    ("Malformed", False, "object", "structurally malformed object or COSE structure (the generic fallback rejection)"),
    ("ContentIdMismatch", False, "object", "the recomputed content id does not equal the carried content id (§2.3)"),
    ("HeaderBodyMismatch", False, "object", "a protected-header routing copy disagrees with the signed body (§2.6)"),
    ("UnsupportedVersion", False, "object", "the protected-header naalp-version is not supported (§2.5.3)"),
    ("UnknownCriticalExt", False, "object", "a critical-extension (cext) key is not understood (§2.5)"),
    ("UnknownKind", False, "object", "the channel/kind code is not a registered surface (§3.2)"),
    ("RangeError", False, "object", "a field value is outside its permitted range"),
    ("NonNFC", False, "object", "a text field is not in Unicode Normalization Form C (§3.1)"),
    ("WrongAudience", False, "object", "the signed audience is not the verifying party (§2.5.3, R1)"),
    # bounds (§3.4)
    ("TooLarge", False, "bounds", "the object exceeds the maximum octet size (§3.4)"),
    ("TooManyCauses", False, "bounds", "causes[] exceeds the maximum count (§3.4)"),
    ("TooManyExtensions", False, "bounds", "the ext or cext map exceeds the maximum cardinality (§3.4)"),
    ("TooManyChunks", False, "bounds", "a stream presents more chunks than the maximum (§3.4, §10)"),
    # crypto / COSE (§4)
    ("UnknownAlg", False, "crypto", "the algorithm id is not in the N-AALP signature registry (§4)"),
    ("KeyAlgMismatch", False, "crypto", "the key algorithm does not match the object header (§4.5)"),
    ("ProfileDowngrade", False, "crypto", "the signature level is below the profile minimum (§4.5)"),
    ("HybridIncomplete", False, "crypto", "a hybrid/composite object has a component signature that does not verify (§4.5)"),
    ("SuiteMismatch", False, "crypto", "the signed suite declaration disagrees with the signature alg or structure (§4.5)"),
    ("CompositeRefused", False, "crypto", "a Sovereign verifier refuses a composite (non-pure) object (§4.5)"),
    ("BadSignature", False, "crypto", "signature verification failed (§4)"),
    # identity / rotation (§5)
    ("SignerMismatch", False, "identity", "the recomputed signer id does not equal the key, or a revocation signer is neither the key nor a configured recovery key (§5.1, §5.3, §5.5)"),
    ("RotationUnauthorized", False, "identity", "a rotation object is not co-signed by both the old and new keys, or is presented as a single-signature object (§5.2)"),
    ("KeyRevoked", False, "identity", "the signing key is revoked as of the object's authoritative receipt position (§5.3)"),
    # effect / policy (§6)
    ("EffectNotAuthorized", False, "effect", "the declared effect is not authorized for the principal (§6)"),
    ("UnauthenticatedPrincipal", False, "effect", "a self-asserted principal was not authenticated by the transport (§6.5, R1.3)"),
    ("MalformedSafetyLabel", False, "effect", "the optional ext safety-label is structurally malformed (§6.4)"),
    # approval / consume (§7)
    ("ApprovalRequired", False, "approval", "an effecting object requires an approval and none was presented (§7)"),
    ("ApprovalMismatch", False, "approval", "the presented approval does not bind the object (§7)"),
    ("ApprovalExpired", False, "approval", "the approval's validity window has passed (§7)"),
    ("AlreadyConsumed", False, "approval", "a consume-once object was already consumed (§7)"),
    ("ConsumeFork", False, "approval", "two consume receipts fork the single-consume ledger (§7)"),
    ("ConsumeForkInvalid", False, "approval", "a presented consume-fork proof is not a valid fork (§7)"),
    ("ConsumeReceiptUnsigned", False, "approval", "a consume receipt is not signed (§7)"),
    ("LedgerCorrupt", False, "approval", "the consume ledger is structurally corrupt (§7)"),
    ("LedgerUnsigned", False, "approval", "a consume-ledger record is not signed (§7)"),
    ("AudienceMismatch", False, "approval", "a consume receipt's audience does not match the object (§7)"),
    ("FreshnessSelfAsserted", False, "approval", "an approval's freshness is only self-asserted, not independently anchored (§7, R-TDCS-4)"),
    # coarse refusal (§7, R-TDCS-3)
    ("UnknownRefusalOutcome", False, "refusal", "a coarse-refusal object carries an unknown outcome value (R-TDCS-3)"),
    ("RefusalDetailLeak", False, "refusal", "a coarse-refusal object discloses detail beyond the coarse vocabulary (R-TDCS-3)"),
    # audit / ordering (§8)
    ("ChainBroken", False, "audit", "an audit or hash-chain link does not verify (§8)"),
    ("Equivocation", False, "audit", "two conflicting signed statements occupy one chain position (§8)"),
    ("CausalViolation", False, "audit", "an object is applied before a declared cause (§8, §13)"),
    ("ReceiptUnsigned", False, "audit", "an authoritative receipt is not signed (§8)"),
    ("ForkProofInvalid", False, "audit", "an audit fork proof is not one signer over two conflicting objects (§8)"),
    # delivery (§9)
    ("StageOutOfOrder", False, "delivery", "a delivery stage arrived out of its required order (§9)"),
    # streaming (§10)
    ("StreamDigestMismatch", False, "streaming", "a stream commit digest does not equal the recomputed rolling digest (§10)"),
    ("StreamStateError", False, "streaming", "a streaming event is illegal for the current stream state (§10 state table)"),
    # transport (§12)
    ("ConfidentialTransportRequired", False, "transport", "an object requiring a confidential transport was received without one (§12)"),
    ("PeerUnauthenticated", False, "transport", "the transport peer is not authenticated (§12)"),
    # carriage (§13)
    ("NotDelivered", True, "carriage", "a carriage delivery did not complete; an unmodified retry may later succeed (§13)"),
    ("MappingError", False, "carriage", "a foreign-carriage mapping could not be applied (§13)"),
    # capability model / channels (§14/§15)
    ("EffectDeclarationMismatch", False, "channels", "a channel object's declared effect disagrees with its kind (§14)"),
    ("StateTransitionError", False, "channels", "a channel state transition is not permitted (§14 state table)"),
    ("CapExceedsParent", False, "channels", "a capability grant exceeds its parent's scope (§14)"),
    ("TransformCycle", False, "channels", "a capability transform graph contains a cycle (§14)"),
    ("InputGateBypass", False, "channels", "a workflow input gate was bypassed (§14)"),
    ("TaskStateError", False, "channels", "a task state transition is not permitted (§14)"),
    ("ScopeOverlapConflict", False, "federation", "two federated scopes overlap in conflict (§15)"),
    ("ReconcileMismatch", False, "federation", "a federated reconcile verifier's independent recomputation disagrees with the presented linearization (§15)"),
    # continuation (channel)
    ("WrongFlow", False, "continuation", "a continuation frame names the wrong flow"),
    ("SeqGap", False, "continuation", "a continuation sequence has a gap"),
    ("AboveCeiling", False, "continuation", "a continuation sequence exceeds its declared ceiling"),
    ("GapDetected", False, "continuation", "a continuation commit detects a missing frame"),
    ("CommitMismatch", False, "continuation", "a continuation commit digest does not match the frames"),
    ("ContMalformed", False, "continuation", "a continuation frame is structurally malformed"),
    # delegation (channel)
    ("GrantExpired", False, "delegation", "a delegation grant's validity window has passed"),
    ("GrantNotYetValid", False, "delegation", "a delegation grant is not yet valid"),
    ("GrantRevoked", False, "delegation", "a delegation grant is revoked"),
    ("UntrustedChainRoot", False, "delegation", "a delegation chain does not root in a trusted grantor"),
    ("DelegationDepthExceeded", False, "delegation", "the declared or realized delegation depth exceeds max_depth"),
    ("GrantMalformed", False, "delegation", "a delegation grant object is structurally malformed"),
    # naming (channel)
    ("NameMalformed", False, "naming", "a naming object is structurally malformed"),
    ("NameChainBroken", False, "naming", "a name-binding chain link does not verify"),
    ("NameForkProofInvalid", False, "naming", "a name fork proof is not one signer over two conflicting bindings"),
    ("IllegalTransition", False, "naming", "a naming state transition is not permitted"),
    ("TaskChainBroken", False, "naming", "an A2A task chain link does not verify"),
    ("ForeignCard", False, "naming", "a foreign agent-card reference is invalid"),
    # description (channel)
    ("DescMalformed", False, "description", "a description object is structurally malformed"),
    ("MalformedApprovalFlag", False, "description", "a description approval flag is malformed"),
    ("DirForkProofInvalid", False, "description", "a directory fork proof is not one signer over two conflicting directory objects"),
    ("ImporterMismatch", False, "description", "a description import's importer does not match"),
    ("UnknownDescriptionFormat", False, "description", "a description carries an unregistered format code"),
    ("VerifierKeyMismatch", False, "description", "a description import's verifier key does not match the declared alg/key"),
    # negotiation (channel)
    ("NegMalformed", False, "negotiation", "a negotiation object is structurally malformed"),
    ("UnknownRole", False, "negotiation", "a negotiation role is unknown"),
    ("UnknownProfile", False, "negotiation", "a negotiation profile is unknown"),
    ("NotDescended", False, "negotiation", "a negotiation accept does not descend from the offer"),
    ("NotOffer", False, "negotiation", "an object expected to be an offer is not one"),
    ("NotAccept", False, "negotiation", "an object expected to be an accept is not one"),
    ("MalformedCriticalFlag", False, "negotiation", "a negotiation critical flag is malformed"),
    ("UnknownCriticalRisk", False, "negotiation", "a negotiation carries an unknown critical risk label"),
    ("ReferenceMismatch", False, "negotiation", "a negotiation trust reference does not match"),
    # mcp (channel)
    ("MalformedAnnotation", False, "mcp", "an MCP tool annotation is malformed"),
    ("EffectUnderDeclared", False, "mcp", "an MCP annotation declares a lower effect than its mapping requires"),
    ("EffectOutsideLattice", False, "mcp", "an MCP annotation maps to an effect outside the closed lattice"),
    ("ToolCallMalformed", False, "mcp", "an MCP tool-call object is malformed"),
    # payment (channel)
    ("PayMalformed", False, "payment", "a payment object is structurally malformed"),
    ("UnknownPaymentFormat", False, "payment", "a payment carries an unregistered format code"),
    # gateway (channel)
    ("GwMalformed", False, "gateway", "a gateway object is structurally malformed"),
    ("UnknownGatewayDecision", False, "gateway", "a gateway decision value is unknown"),
    # ag-ui (channel)
    ("UIMalformed", False, "agui", "an AG-UI event object is malformed"),
    ("UIChainBroken", False, "agui", "an AG-UI event chain link does not verify"),
    ("UnknownUIEventKind", False, "agui", "an AG-UI event kind is unknown"),
    ("ActionSubstituted", False, "agui", "an AG-UI action was substituted between render and confirm"),
    ("UINoConsent", False, "agui", "an AG-UI effecting action lacks recorded user consent"),
    # rooms (channel)
    ("StaleEpoch", False, "rooms", "a room operation names a stale membership epoch"),
    ("Unauthorized", False, "rooms", "a room operation is not authorized for the principal"),
    ("OwnerImmutable", False, "rooms", "a room owner cannot be changed by this operation"),
    ("MemberExists", False, "rooms", "a room member add conflicts with an existing member"),
    ("MemberUnknown", False, "rooms", "a room operation names an unknown member"),
    ("OwnerExists", False, "rooms", "a room create conflicts with an existing owner"),
    ("RoleInvalid", False, "rooms", "a room role value is invalid"),
    ("RoomOpMismatch", False, "rooms", "a room operation kind does not match its payload"),
    ("OpUnknown", False, "rooms", "a room operation kind is unknown"),
    ("PrincipalUnknown", False, "rooms", "a room operation names an unknown principal"),
    ("PrincipalExists", False, "rooms", "a room principal add conflicts with an existing principal"),
    ("RebindUnauthorized", False, "rooms", "a room principal rebind is not authorized"),
    # evidence-record family (design.md §26; decision-record, checkpoint-root/witness-cosign/
    # inclusion-proof, egress-attestation, ordering-disclosure, foreign-profile-pin)
    ("EgMalformed", False, "gateway", "an egress-attestation object is structurally malformed"),
    ("UnknownEgressBinding", False, "gateway", "an egress-attestation binding value is outside the closed content-bound/content-free set"),
    ("DecisionMalformed", False, "gateway", "a decision-record object is structurally malformed, or a deny/hold outcome carries a consume reference"),
    ("UnknownOrderingBasis", False, "gateway", "an ordering-disclosure basis value is outside the closed correspondence-only/single-boundary/external-mechanism set"),
    ("OrderingDisclosureMalformed", False, "gateway", "an ordering-disclosure group violates its basis-conditioned field well-formedness"),
    ("TermDispositionMalformed", False, "gateway", "a decision-record terms map carries a key outside the record's own field set"),
    ("CheckpointMalformed", False, "audit", "a checkpoint-root object is structurally malformed"),
    ("WitnessRootMismatch", False, "audit", "a witness-cosign names a root content id that does not match the checkpoint it accompanies"),
    ("InclusionProofInvalid", False, "audit", "an inclusion-proof audit path does not recompute to the named checkpoint root"),
    ("ForeignProfileMalformed", False, "gateway", "a foreign-profile-pin object is structurally malformed"),
    # manufacturing physical-hazard (Mfg-F; the hazard dimension orthogonal to effect)
    ("HazardMalformed", False, "hazard", "a naalp-hazard-claim or naalp-hazard-authorization body is structurally malformed (wrong shape; a spatial-bounds axis with min greater than max; empty axes; or a non-NFC frame)"),
    ("HazardNotCovered", False, "hazard", "a well-formed hazard claim's class or envelope is not fully covered by the presented hazard authorization (class/frame/axis-count mismatch; or an axis/speed/window bound outside the grant)"),
    ("HazardUnknown", False, "hazard", "an action requiring a hazard declaration carries none or carries an unrecognized hazard value (normalized to the fail-closed class; returned when no claim exists to check coverage against)"),
]

# name -> code, code -> name
CODE = {name: i + 1 for i, (name, _r, _s, _d) in enumerate(CANON)}
NAME = {i + 1: name for i, (name, _r, _s, _d) in enumerate(CANON)}
STANDARDS_MAX = 0x7FFF  # >= 0x8000 is private-use (no registration)


def naalp_error_body(code, name, detail=None, subject=None):
    """Canonical CBOR of the naalp-error body map {1:code, 2:name, ?3:detail, ?4:subject}.
    Integer keys 1..4 are already in canonical ascending order."""
    pairs = [(1, code), (2, name)]
    if detail is not None:
        pairs.append((3, detail))
    if subject is not None:
        pairs.append((4, subject))
    return enc(("map", pairs))


def build():
    errors = [{"code": i + 1, "name": name, "retryable": retry, "subsystem": sub, "desc": desc}
              for i, (name, retry, sub, desc) in enumerate(CANON)]
    # ordered name array: NameForCode(code) == names[code-1]; code == index+1. This is the minimal
    # representation each port embeds (an ordered list of names), and the source the port table is
    # graded against by the error.name_for_code op.
    names = [name for (name, _r, _s, _d) in CANON]

    # error.encode KATs: a representative spread of codes (short/long names, the extremes) plus the
    # two full-grammar cases carrying detail (field 3) and a real content-id-shaped subject (field 4;
    # multihash 0x20/sha2-384 + 48-octet digest). One or two per subsystem is enough to grade the
    # body encoding across all ten adapters -- the per-code TABLE is graded by error.name_for_code.
    subj = bytes([0x20, 0x30]) + bytes(range(48))
    enc_specs = [
        ("NonCanonical", None, None), ("Malformed", None, None), ("WrongAudience", None, None),
        ("BadSignature", None, None), ("NotDelivered", None, None), ("ScopeOverlapConflict", None, None),
        ("ReconcileMismatch", None, None), ("RebindUnauthorized", None, None),
        ("BadSignature", "verifier reason: see log", subj.hex()),
        ("WrongAudience", "audience was other-endpoint", subj.hex()),
    ]
    encode_cases = []
    for i, (nm, detail, subj_hex) in enumerate(enc_specs, 1):
        s = None if subj_hex is None else bytes.fromhex(subj_hex)
        encode_cases.append({
            "tcId": i, "code": CODE[nm], "name": nm, "detail": detail, "subject_hex": subj_hex,
            "want_hex": naalp_error_body(CODE[nm], nm, detail, s).hex(),
        })

    # error.decode KATs: canonical round-trips (accept), the dual-carriage MUST-REJECT (registered
    # code with the wrong registered name -> Malformed), and the unknown-code opaque case (accept).
    decode_cases = []
    di = 0
    for nm in ("NonCanonical", "BadSignature", "NotDelivered", "RebindUnauthorized"):
        di += 1
        decode_cases.append({
            "tcId": di, "in_hex": naalp_error_body(CODE[nm], nm).hex(),
            "want": {"code": CODE[nm], "name": nm}, "reject": None,
            "note": "canonical %s round-trips" % nm,
        })
    di += 1
    decode_cases.append({
        "tcId": di, "in_hex": naalp_error_body(CODE["BadSignature"], "NotDelivered").hex(),
        "want": None, "reject": "Malformed",
        "note": "code=22 (BadSignature) but name=NotDelivered: registered code + wrong name -> Malformed",
    })
    di += 1
    unknown = 60000  # standards-range but unassigned in this document
    decode_cases.append({
        "tcId": di, "in_hex": naalp_error_body(unknown, "SomeFutureError").hex(),
        "want": {"code": unknown, "name": "SomeFutureError"}, "reject": None,
        "note": "unknown code is opaque and non-fatal (open registry, RFC Required)",
    })

    return {
        "channel": 0, "kind": 3,  # Control/Error surface (§3.2)
        "standards_max": STANDARDS_MAX,
        "unknown_code_example": unknown,
        "errors": errors,
        "names": names,
        "encode_cases": encode_cases,
        "decode_cases": decode_cases,
    }


def write_cases(doc):
    outdir = os.path.join(ROOT, "vectors", "error_codes")
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "cases.json"), "w", newline="\n", encoding="utf-8") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")


def write_csv(doc):
    # vectors/registry/error-codes.csv is the human-readable registry authority, generated from the
    # same CANON as the byte cases so the two cannot drift; the drift gate checks CSV <-> CDDL enum.
    outdir = os.path.join(ROOT, "vectors", "registry")
    lines = ["code,name,retryable,subsystem,description"]
    for e in doc["errors"]:
        # description has no commas by construction; quote defensively anyway.
        desc = e["desc"].replace('"', "'")
        lines.append('%d,%s,%s,%s,"%s"' % (e["code"], e["name"],
                                           "yes" if e["retryable"] else "no", e["subsystem"], desc))
    # encoding="utf-8" is REQUIRED for cross-platform byte-determinism: without it, text
    # mode uses the platform default (cp1252 on Windows, utf-8 on Linux CI), so the "§"
    # in subsystem-section descriptions encodes as 0xA7 vs 0xC2A7 and the file's pinned
    # SHA-256 drifts between a Windows-authored commit and the Linux CI regeneration.
    with open(os.path.join(outdir, "error-codes.csv"), "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def cddl_enum(doc):
    """Emit the `naalp-error-code` CDDL enum block (for insertion into spec/naalp-draft-01.cddl).
    The body grammar uses `code: uint` (NOT this enum) so a future/private code still validates;
    this enum is the named taxonomy the drift gate checks the CSV against."""
    lines = ["naalp-error-code = &("]
    for e in doc["errors"]:
        lines.append("  %s: %d," % (e["name"], e["code"]))
    lines.append(")")
    return "\n".join(lines)


if __name__ == "__main__":
    doc = build()
    write_cases(doc)
    write_csv(doc)
    print("error_codes_oracle: %d registered errors (codes 1..%d); %d encode + %d decode cases"
          % (len(doc["errors"]), len(doc["errors"]), len(doc["encode_cases"]), len(doc["decode_cases"])))
    retry = [e["name"] for e in doc["errors"] if e["retryable"]]
    print("retryable:", retry)
    if "--cddl" in sys.argv:
        print("\n--- naalp-error-code CDDL enum ---")
        print(cddl_enum(doc))
