# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP §2.3 content-id multihash oracle (design.md §2.3, R19). Constructs, from scratch and
independent of impl/go and impl/rust, the byte authority for the object content id framing:

    id = multihash(0x20, SHA-384(canonical-body-without-field-1))

EVERY OTHER PLACE IN THIS TREE THAT PRODUCES THIS FRAMING HARDCODES THE TWO PREFIX BYTES
------------------------------------------------------------------------------------------
tools/envelope_oracle.py, tools/determinism_oracle.py, and impl/go/cbor/cbor.go all write
`b"\\x20\\x30"` / `0x20, 0x30` directly as two literal bytes -- correct, but never derived
from the multiformats varint algorithm those bytes are instances of. This oracle is the first
in the tree to build a GENERIC unsigned-varint encoder/decoder (multi-byte capable, not just
the two single-byte values N-AALP happens to need) and DERIVE 0x20 and 0x30 from it, so the
hardcoded shortcut used everywhere else is proven correct rather than merely assumed.

TWO INDEPENDENT AUTHORITIES (F3 non-circular)
----------------------------------------------
1. The multiformats unsigned-varint spec (https://github.com/multiformats/unsigned-varint):
   LEB128-style base-128 groups, 7 payload bits per byte, high bit set on every byte except
   the last. This module implements it generically: encode_uvarint/decode_uvarint round-trip
   any non-negative integer, not only values < 128. A self-check below hand-derives the
   two-byte encoding of 300 (0xAC 0x02) and asserts the generic encoder reproduces it, proving
   multi-byte support before it is trusted for the (single-byte, coincidentally) N-AALP case.
2. NIST FIPS 180-4 SHA-384 known-answer digests, computed here via Python's hashlib (the
   standard SHA-384 primitive every oracle in tools/ already treats as the trusted hash
   authority -- see cbor_oracle.py, determinism_oracle.py). The published FIPS 180-4 digests
   for the empty string and "abc" are asserted byte-for-byte against hashlib's output as a
   check that hashlib itself agrees with the published KAT before its output for the third
   (112-octet, RFC 6234 section 8.5 "TEST2") message is trusted for a vector this oracle
   did not receive a pre-published digest for.

The multicodec code for sha2-384 is 0x20 (status: permanent, "as specified by FIPS 180-4",
multiformats/multicodec code table). Cross-referenced neighbours sha2-256 = 0x12 and
sha2-512 = 0x13 appear below only as a real, registered "wrong code" reject fixture -- not as
values this oracle needs to construct N-AALP content ids.

Generated by tools/multihash_oracle.py; do not hand-edit vectors/multihash/cases.json.
"""
import hashlib
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------------------
# multiformats unsigned-varint (generic; multi-byte capable)
# ---------------------------------------------------------------------------------------

def encode_uvarint(n):
    """LEB128-style unsigned varint (multiformats unsigned-varint spec): 7 payload bits per
    byte, continuation bit (0x80) set on every byte except the last. Handles any n >= 0, not
    only n < 128 -- the single-byte case N-AALP happens to use is the n < 128 special case of
    this general algorithm, not a separate rule."""
    if not isinstance(n, int) or n < 0:
        raise ValueError("uvarint: n must be a non-negative integer, got %r" % (n,))
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        if n:
            out.append(b | 0x80)
        else:
            out.append(b)
            break
    return bytes(out)


def decode_uvarint(data, offset=0):
    """Inverse of encode_uvarint. Returns (value, new_offset). Raises ValueError on a varint
    that runs off the end of `data` (truncated) or that never terminates within 64 bits
    (malformed)."""
    result = 0
    shift = 0
    pos = offset
    while True:
        if pos >= len(data):
            raise ValueError("VarintTruncated: ran out of bytes decoding a uvarint at offset %d" % offset)
        b = data[pos]
        pos += 1
        result |= (b & 0x7F) << shift
        if not (b & 0x80):
            return result, pos
        shift += 7
        if shift > 63:
            raise ValueError("VarintTooLong: uvarint at offset %d exceeds 64 bits" % offset)


# ---------------------------------------------------------------------------------------
# multihash construction / parsing (multiformats multihash spec: uvarint(code) ||
# uvarint(digest-length) || digest)
# ---------------------------------------------------------------------------------------

SHA2_384_CODE = 0x20   # multicodec table: sha2-384, status permanent, "as specified by FIPS 180-4"
SHA2_384_LEN = 48      # SHA-384 digest length in octets
SHA2_256_CODE = 0x12   # multicodec table: sha2-256 (cross-ref; used only as a "wrong code" fixture)
SHA2_512_CODE = 0x13   # multicodec table: sha2-512 (cross-ref only; not used to build a vector)


def encode_multihash(code, digest):
    """multihash(code, digest) = uvarint(code) || uvarint(len(digest)) || digest."""
    return encode_uvarint(code) + encode_uvarint(len(digest)) + digest


def decode_multihash(data):
    """Parse a multihash generically: code varint, length varint, then exactly `length`
    digest bytes with NOTHING left over. Returns (code, length, digest). Raises ValueError,
    naming one of MultihashTruncated (fewer digest bytes present than declared) or
    MultihashOverLong (more bytes present than declared -- a wrong/too-small length octet or
    unrelated trailing bytes are the same wire symptom: undeclared bytes after the digest)."""
    code, pos = decode_uvarint(data, 0)
    length, pos = decode_uvarint(data, pos)
    remaining = len(data) - pos
    if remaining < length:
        raise ValueError("MultihashTruncated: declared digest length %d, only %d byte(s) present"
                         % (length, remaining))
    if remaining > length:
        raise ValueError("MultihashOverLong: declared digest length %d, %d byte(s) present "
                         "(%d trailing byte(s) beyond the declared digest)"
                         % (length, remaining, remaining - length))
    digest = data[pos:pos + length]
    return code, length, digest


def validate_naalp_content_id(data):
    """Structural AND semantic validation of an N-AALP content id (design.md §2.3): a
    well-formed multihash (decode_multihash) whose code is sha2-384 (0x20) and whose digest
    is exactly 48 octets. Returns the 48-byte digest on success; raises ValueError naming
    WrongMultihashCode or WrongDigestLength on a structurally-valid-but-wrong multihash."""
    code, length, digest = decode_multihash(data)
    if code != SHA2_384_CODE:
        raise ValueError("WrongMultihashCode: multihash code 0x%02x, N-AALP content ids "
                         "require sha2-384 (0x20)" % code)
    if length != SHA2_384_LEN or len(digest) != SHA2_384_LEN:
        raise ValueError("WrongDigestLength: declared digest length %d, SHA-384 requires 48"
                         % length)
    return digest


# ---------------------------------------------------------------------------------------
# NIST FIPS 180-4 SHA-384 known-answer digests (independent source #2)
# ---------------------------------------------------------------------------------------

# Published FIPS 180-4 SHA-384 digests, typed verbatim from the standard (independent of this
# tree's hashlib call below -- these two lines are the authority hashlib is checked against,
# not the other way around).
FIPS_SHA384_ABC = "cb00753f45a35e8bb5a03d699ac65007272c32ab0eded1631a8b605a43ff5bed8086072ba1e7cc2358baeca134c825a7"
FIPS_SHA384_EMPTY = "38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b"

# RFC 6234 §8.5 "TEST2" -- the standard 112-octet two-block SHA-384/512 test message (the same
# message FIPS 180-4's own worked examples exercise). No pre-published digest is hand-typed
# for it here; its digest is computed via hashlib.sha384 below, which by that point has already
# been proven to reproduce the two hand-typed FIPS digests above byte-for-byte.
RFC6234_TEST2_MSG = ("abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmno"
                     "ijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu")


def sha384_hex(msg_bytes):
    return hashlib.sha384(msg_bytes).hexdigest()


def build():
    # ---- Independent authority #2 self-check: hashlib.sha384 against the two hand-typed
    # published FIPS 180-4 digests, BEFORE it is trusted for the third (unpublished-here) input.
    got_empty = sha384_hex(b"")
    got_abc = sha384_hex(b"abc")
    assert got_empty == FIPS_SHA384_EMPTY, "hashlib SHA-384('') disagrees with FIPS 180-4"
    assert got_abc == FIPS_SHA384_ABC, "hashlib SHA-384('abc') disagrees with FIPS 180-4"
    assert len(RFC6234_TEST2_MSG) == 112, "RFC 6234 TEST2 message must be exactly 112 octets"
    got_test2 = sha384_hex(RFC6234_TEST2_MSG.encode("ascii"))

    # ---- Independent authority #1 self-check: the generic multi-byte uvarint round-trips a
    # value >= 128 and matches a HAND-derived two-byte encoding, proving multi-byte support
    # before the single-byte N-AALP case (which alone could hide a single-byte-only bug).
    # 300 = 0b1_0010_1100 -> low 7 bits 0101100 (0x2C) with continuation -> 0xAC;
    #                        remaining bits 10 (0x02), final byte -> 0x02.
    assert encode_uvarint(300) == bytes([0xAC, 0x02]), "uvarint(300) must be AC 02 (hand-derived)"
    rt_val, rt_pos = decode_uvarint(bytes([0xAC, 0x02]))
    assert (rt_val, rt_pos) == (300, 2), "uvarint round-trip of AC 02 must recover (300, 2)"

    # ---- The two single-byte values N-AALP actually uses, DERIVED (not hardcoded) from the
    # same generic algorithm just proven multi-byte-capable above.
    code_octet = encode_uvarint(SHA2_384_CODE)
    len_octet = encode_uvarint(SHA2_384_LEN)
    assert code_octet == b"\x20", "derived sha2-384 code octet must be 0x20"
    assert len_octet == b"\x30", "derived 48-octet length octet must be 0x30"

    accept = []
    for name, msg_bytes, digest_hex in (
        ("sha384_empty", b"", got_empty),
        ("sha384_abc", b"abc", got_abc),
        ("sha384_rfc6234_test2", RFC6234_TEST2_MSG.encode("ascii"), got_test2),
    ):
        digest = bytes.fromhex(digest_hex)
        mh = encode_multihash(SHA2_384_CODE, digest)
        # Round-trip through the generic decoder and the N-AALP semantic validator before
        # this vector is trusted as an "accept" fixture.
        code, length, dg = decode_multihash(mh)
        assert (code, length, dg) == (SHA2_384_CODE, SHA2_384_LEN, digest)
        assert validate_naalp_content_id(mh) == digest, (
            "accept vector %r: validate_naalp_content_id returned a digest that does not "
            "match the recorded digest_hex" % name)
        assert mh[:2] == b"\x20\x30" and len(mh) == 50
        accept.append({
            "name": name,
            "input_ascii": msg_bytes.decode("ascii"),
            "input_len": len(msg_bytes),
            "digest_hex": digest_hex,
            "multihash_hex": mh.hex(),
        })

    # ---- Must-REJECT cases: each is an otherwise-plausible multihash carrying exactly one
    # violation, over the "abc" digest so the digest bytes themselves are never in question.
    base_digest = bytes.fromhex(got_abc)
    reject = []

    # wrong length octet: declares 47 (0x2f) while the full 48-byte digest follows -> one
    # undeclared trailing byte -> MultihashOverLong. This is literally the "20 2f ..." example.
    wrong_len = bytes([SHA2_384_CODE, 0x2F]) + base_digest
    reject.append({"name": "wrong_length_octet", "multihash_hex": wrong_len.hex(),
                   "error": "MultihashOverLong",
                   "note": "length octet 0x2f (47) instead of 0x30 (48) with the full "
                           "48-byte digest present -- 1 undeclared trailing byte"})

    # wrong code: a structurally well-formed multihash (correct length octet, correct 48-byte
    # digest) but the sha2-256 code (0x12) instead of sha2-384 (0x20, real registered codes).
    wrong_code = encode_multihash(SHA2_256_CODE, base_digest)
    reject.append({"name": "wrong_code", "multihash_hex": wrong_code.hex(),
                   "error": "WrongMultihashCode",
                   "note": "multihash code 0x12 (sha2-256, a real registered code) instead of "
                           "0x20 (sha2-384); decode_multihash succeeds structurally, "
                           "validate_naalp_content_id rejects it semantically"})

    # truncated digest: declares 48 but only 40 bytes actually follow.
    truncated = bytes([SHA2_384_CODE, SHA2_384_LEN]) + base_digest[:40]
    reject.append({"name": "truncated_digest", "multihash_hex": truncated.hex(),
                   "error": "MultihashTruncated",
                   "note": "declares a 48-byte digest but only 40 bytes are present"})

    # over-long digest: declares 48 (correct length octet), full 48-byte digest present, PLUS
    # 2 unrelated trailing bytes.
    over_long = encode_multihash(SHA2_384_CODE, base_digest) + b"\xde\xad"
    reject.append({"name": "over_long_digest", "multihash_hex": over_long.hex(),
                   "error": "MultihashOverLong",
                   "note": "correct 0x30 length octet and full 48-byte digest, plus 2 "
                           "unrelated trailing bytes beyond the declared digest"})

    # Confirm every reject vector is rejected by decode_multihash and/or the N-AALP validator,
    # and that the specific error named above is the one actually raised (not merely "some
    # error") -- this is the oracle's own mutation-surviving proof: build() itself would fail
    # if any reject vector were accidentally well-formed.
    for r in reject:
        data = bytes.fromhex(r["multihash_hex"])
        try:
            validate_naalp_content_id(data)
            raise AssertionError("reject vector %r was ACCEPTED -- oracle bug" % r["name"])
        except ValueError as e:
            msg = str(e)
            assert msg.startswith(r["error"] + ":"), (
                "reject vector %r raised %r, expected error class %r"
                % (r["name"], msg, r["error"]))

    return {
        "note": ("Independent oracle output for the N-AALP §2.3 content-id multihash framing "
                "(multihash(0x20, SHA-384(body-without-1))). encode_uvarint/decode_uvarint "
                "implement the multiformats unsigned-varint spec generically (multi-byte "
                "capable, proven on n=300 before use); the sha2-384 code octet (0x20) and the "
                "48-byte length octet (0x30) are DERIVED from that algorithm, not hardcoded. "
                "SHA-384 digests are computed via hashlib, cross-checked against two published "
                "FIPS 180-4 known-answer digests (empty string, 'abc') before being trusted "
                "for the third (RFC 6234 section 8.5 TEST2, 112 octets). "
                "Generated by tools/multihash_oracle.py; do not hand-edit."),
        "varint_selfcheck": {"n": 300, "encoded_hex": "ac02", "note": "hand-derived LEB128"},
        "accept": accept,
        "reject": reject,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "multihash"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    for a in data["accept"]:
        print("  accept", a["name"], "->", a["multihash_hex"][:12], "...", len(a["multihash_hex"]) // 2, "bytes")
    for r in data["reject"]:
        print("  reject", r["name"], "->", r["error"])
    print("wrote", path)


if __name__ == "__main__":
    main()
