# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP `reconcile.state` conformance oracle (ietf/draft-bubblefish-naalp-01.md "## Reconcile
state machine" under "# Object State Machines"; impl/go/federation/federation.go
VerifyReconcileOrder). Constructs, from scratch, the F3 non-circular reference for the Reconcile state
machine: every case's expected {valid, error} outcome is HARDCODED here, read off the draft's
normative table and the single-fault input structure it is built from, and carries an inline
comment naming the exact table row it encodes. This oracle NEVER imports or calls federation, audit,
or any impl package — it does not know the implementation exists. It reuses only the shared,
already-graded deterministic-CBOR constructor (tools/cbor_oracle.py, graded in T1) to build
byte-correct receipt bodies/heads, and its own from-scratch Kahn's linearization (mirroring
tools/federation_oracle.py's independent constructor) to compute the one deterministic order a
`verify` case is judged against.

The reconcile machine (draft "## Reconcile state machine") has states collecting (per-authority
receipt chains are being gathered), linearized (the deterministic total order has been computed),
verified. Events: add-chain (a per-authority receipt chain is added to the merge), linearize (the
deterministic linearization is computed over the accumulated chains), verify (an independent
recomputation is compared against a claimed total order).

Table rows encoded (draft "## Reconcile state machine"):
  collecting | add-chain (valid link, no equivocation)                  -> collecting
  collecting | add-chain (broken prev/seq link)                         -> reject ChainBroken
  collecting | add-chain (two receipts, one seq, different objects)     -> reject Equivocation
  collecting | add-chain (receipt signature does not verify)            -> reject ReceiptUnsigned
  collecting | linearize (union causal graph acyclic, no future-cause)  -> linearized
  collecting | linearize (cycle or future-cause in the merged graph)    -> reject CausalViolation
  linearized | verify (independent recomputation agrees)                -> verified
  linearized | verify (independent recomputation disagrees)             -> reject ReconcileMismatch

What the "add-chain" cases drive: the draft specifies a FIXED pipeline (VerifyChain over the
per-authority chain, then each receipt observed for equivocation) with no precedence among the
three add-chain faults ("rejected under its own already-registered name," no ordering stated) — so
every add-chain case here carries EXACTLY ONE fault, making the verdict independent of adapter
sequencing:
  - valid:            a single well-linked, correctly-signed receipt; no extra observation.
  - ChainBroken:       a second receipt whose `prev` does not link to the first receipt's head
                       (structurally self-consistent otherwise — VerifyChain rejects the LINK
                       before it ever reaches the signature check).
  - ReceiptUnsigned:   a single receipt whose signature byte is corrupted after construction
                       (correct prev/seq/obj/at — VerifyChain reaches and fails the sig check).
  - Equivocation:      a single valid receipt (passes VerifyChain + is Observed cleanly), PLUS one
                       EXTRA receipt presented to the SAME auditor claiming the identical seq but a
                       DIFFERENT object — VerifyChain never sees the extra (it is not part of the
                       `chain` array VerifyChain checks; a chain array cannot itself carry a
                       duplicate seq without independently tripping ChainBroken, since VerifyChain
                       requires receipts[i].Seq == i positionally) — only Observe sees it, and
                       Observe keys purely on Seq/Obj, ignoring Prev.

What "linearize" and "verify" drive: linearize is graded by whether the accumulated node set is a
valid partial order (Reconcile/VerifyCausal); verify is graded by comparing a CLAIMED total order
against the oracle's OWN independent Kahn's linearization (content-id, bytewise-ascending
tie-break — mirroring tools/federation_oracle.py's `reconcile`, never the impl's). The mismatch
case's claim is a CAUSALLY-VALID permutation (two causally-independent nodes swapped), not a
causally-invalid one — a causally-invalid claim would make the verdict arguable
Mismatch-vs-CausalViolation, a cell the draft does not adjudicate, so it is deliberately not graded.

Every case grades ONLY {valid, error} (this state machine's op has no ledger/stage side-channel to
grade, unlike delivery.state/approval.state). Generated by tools/reconcile_state_oracle.py; do not
hand-edit vectors/reconcile_state/cases.json.
"""
import hashlib
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cbor_oracle  # shared RFC-8949 deterministic-CBOR constructor (graded in T1)

GENESIS = b"\x00" * 48  # HeadSize (SHA-384) zero genesis prev


def cid(name):
    """Content id (T1 framing multihash 0x20 0x30 || SHA-384) of a tiny worked object {1: name}."""
    b = cbor_oracle.encode(("map", [(1, name)]))
    return b"\x20\x30" + hashlib.sha384(b).digest()


def receipt_bytes(prev, obj, seq, at):
    """Deterministic-CBOR receipt body {1: prev, 2: obj, 3: seq, 4: at} (audit.Receipt.Bytes)."""
    return cbor_oracle.encode(("map", [(1, prev), (2, obj), (3, seq), (4, at)]))


def head(body):
    """Chain head after a receipt: SHA-384 of its body (audit.Receipt.Head)."""
    return hashlib.sha384(body).digest()


def receipt_spec(prev, obj, seq, at):
    return {"prev_hex": prev.hex(), "obj_hex": obj.hex(), "seq": seq, "at": at,
            "body_hex": receipt_bytes(prev, obj, seq, at).hex()}


def reconcile_order(nodes):
    """Independent Kahn's linearization, tie-broken by content id (bytewise ascending) —
    mirrors tools/federation_oracle.py's `reconcile`; never the impl. `nodes` is a list of
    (id_bytes, causes_bytes_list)."""
    ids = [n[0] for n in nodes]
    causes = {n[0]: [c for c in n[1] if c in ids] for n in nodes}
    indeg = {i: len(causes[i]) for i in ids}
    emitted = []
    done = set()
    while len(emitted) < len(ids):
        ready = sorted(i for i in ids if i not in done and indeg[i] == 0)  # bytewise tie-break
        pick = ready[0]
        done.add(pick)
        emitted.append(pick)
        for i in ids:
            if i not in done and pick in causes[i]:
                indeg[i] -= 1
    return emitted


def expect(valid, error):
    return {"valid": valid, "error": error}


def build():
    cases = []

    def add(tc_id, name, table_row, event, fields, expected):
        c = {"tcId": tc_id, "name": name, "table_row": table_row, "event": event}
        c.update(fields)
        c["expected"] = expected
        cases.append(c)

    # ---- add-chain (state: collecting) --------------------------------------------------
    a = cid("reconcile-objA")
    b = cid("reconcile-objB")
    x = cid("reconcile-objX")  # distinct from A/B — used for the equivocation fault

    # tc1: a single well-linked, correctly-signed receipt; nothing else observed.
    r0 = receipt_spec(GENESIS, a, 0, 100)
    add(1, "add-chain-valid",
        "collecting | add-chain (valid link, no equivocation) | -> collecting",
        "add-chain", {"chain": [r0], "extra": None, "corrupt_sig_at": None},
        expect(True, ""))

    # tc2: ChainBroken — a second receipt whose prev does NOT link to head(r0) (it links to
    # genesis instead), structurally self-consistent otherwise. VerifyChain rejects the broken
    # link before it ever reaches the signature check (impl/go/audit/audit.go VerifyChain).
    r0b = receipt_spec(GENESIS, a, 0, 100)
    r1_broken = receipt_spec(GENESIS, b, 1, 101)  # should be prev=head(r0b), not GENESIS
    add(2, "add-chain-chainbroken",
        "collecting | add-chain (broken prev/seq link) | reject (ChainBroken)",
        "add-chain", {"chain": [r0b, r1_broken], "extra": None, "corrupt_sig_at": None},
        expect(False, "ChainBroken"))

    # tc3: Equivocation — chain=[r0] passes VerifyChain and is Observed cleanly (seq 0 -> obj A);
    # a separate EXTRA receipt then claims the SAME seq (0) with a DIFFERENT object (X). VerifyChain
    # never sees `extra` (a chain array cannot itself carry seq 0 twice without independently
    # tripping ChainBroken on the positional index check); only Observe sees it, and Observe keys
    # purely on Seq/Obj, ignoring Prev — so `extra.prev_hex` is immaterial and left as genesis.
    r0c = receipt_spec(GENESIS, a, 0, 100)
    extra_eq = receipt_spec(GENESIS, x, 0, 101)  # same seq (0) as r0c, different object
    add(3, "add-chain-equivocation",
        "collecting | add-chain (two receipts, one seq, different objects) | reject (Equivocation)",
        "add-chain", {"chain": [r0c], "extra": extra_eq, "corrupt_sig_at": None},
        expect(False, "Equivocation"))

    # tc4: ReceiptUnsigned — a single receipt with correct prev/seq/obj/at; the adapter corrupts
    # the SIGNATURE byte after signing (index 0 in `chain`), so VerifyChain's link check passes and
    # its signature check fails.
    r0d = receipt_spec(GENESIS, a, 0, 100)
    add(4, "add-chain-receiptunsigned",
        "collecting | add-chain (receipt signature does not verify) | reject (ReceiptUnsigned)",
        "add-chain", {"chain": [r0d], "extra": None, "corrupt_sig_at": 0},
        expect(False, "ReceiptUnsigned"))

    # ---- linearize (state: collecting -> linearized) ------------------------------------
    # tc5: valid — an acyclic, no-future-cause union causal graph (P at position 0, Q at position 1
    # caused by P). Reconcile/VerifyCausal accepts it -> collecting transitions to linearized.
    p_lin, q_lin = cid("reconcile-lin-P"), cid("reconcile-lin-Q")
    add(5, "linearize-valid",
        "collecting | linearize (union causal graph acyclic, no future-cause) | -> linearized",
        "linearize",
        {"nodes": [
            {"id_hex": p_lin.hex(), "causes_hex": [], "position": 0},
            {"id_hex": q_lin.hex(), "causes_hex": [p_lin.hex()], "position": 1},
        ]},
        expect(True, ""))

    # tc6: CausalViolation — a two-node mutual cycle in the merged graph (mirrors the Go unit
    # test's cyclic case: C causes D, D causes C). Reconcile/VerifyCausal rejects it fail-closed
    # before any linearization is produced.
    c_lin, d_lin = cid("reconcile-lin-C"), cid("reconcile-lin-D")
    add(6, "linearize-causalviolation",
        "collecting | linearize (cycle or future-cause in the merged graph) | reject (CausalViolation)",
        "linearize",
        {"nodes": [
            {"id_hex": c_lin.hex(), "causes_hex": [d_lin.hex()], "position": 1},
            {"id_hex": d_lin.hex(), "causes_hex": [c_lin.hex()], "position": 1},
        ]},
        expect(False, "CausalViolation"))

    # ---- verify (state: linearized -> verified) -----------------------------------------
    # Two causally-INDEPENDENT objects (no cause between them, both position 0): Reconcile orders
    # concurrent objects by content id bytewise-ascending, so the ONE deterministic order is the
    # bytewise-sorted pair. Both verify cases share this node set; only the claimed order differs.
    v1, v2 = cid("reconcile-verify-1"), cid("reconcile-verify-2")
    verify_nodes = [
        {"id_hex": v1.hex(), "causes_hex": [], "position": 0},
        {"id_hex": v2.hex(), "causes_hex": [], "position": 0},
    ]
    deterministic_order = reconcile_order([(v1, []), (v2, [])])  # oracle's OWN Kahn's, never the impl's
    assert deterministic_order == sorted([v1, v2]), "concurrent nodes order by content id"
    swapped_order = list(reversed(deterministic_order))  # a causally-VALID but non-deterministic permutation

    # tc7: verify agrees — the claimed order IS the oracle's own deterministic linearization.
    add(7, "verify-agrees",
        "linearized | verify (independent recomputation agrees) | -> verified",
        "verify",
        {"nodes": verify_nodes, "claimed_order_hex": [o.hex() for o in deterministic_order]},
        expect(True, ""))

    # tc8: verify ReconcileMismatch — the claimed order is a causally-VALID-but-different
    # permutation (the two objects are concurrent, so the swap is causally valid) — NOT the
    # deterministic order. A causally-INVALID claim is deliberately not used here (that would make
    # the verdict arguable Mismatch-vs-CausalViolation, a cell the draft does not adjudicate).
    add(8, "verify-reconcilemismatch",
        "linearized | verify (independent recomputation disagrees) | reject (ReconcileMismatch)",
        "verify",
        {"nodes": verify_nodes, "claimed_order_hex": [o.hex() for o in swapped_order]},
        expect(False, "ReconcileMismatch"))

    return {
        "note": "Independent F3 non-circular oracle for N-AALP reconcile.state (ietf draft '## "
                "Reconcile state machine' under '# Object State Machines'). add-chain cases build "
                "receipt(s) from hardcoded, byte-correct (deterministic-CBOR) bodies and drive them "
                "through a fixed VerifyChain-then-Observe pipeline with exactly one injected fault; "
                "linearize cases drive a causal node set through Reconcile/VerifyCausal; verify "
                "cases compare a claimed total order against this oracle's OWN independent Kahn's "
                "linearization (content-id tie-break), never the impl's. Every case grades {valid, "
                "error} only. Generated by tools/reconcile_state_oracle.py; do not hand-edit.",
        "cases": cases,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "reconcile_state"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    assert len(data["cases"]) == 8, "expected exactly 8 cases, got %d" % len(data["cases"])
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    for c in data["cases"]:
        print("  tc%02d %-28s -> %s" % (c["tcId"], c["name"], c["expected"]))
    print("wrote", path, "(%d cases)" % len(data["cases"]))


if __name__ == "__main__":
    main()
