# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP C4 independent oracle: the self-certifying signer identifier (design.md §5.1),
identical in form to the N-PAMP PeerHandle:

    signer = multibase(base32, multihash(0x12, SHA-256(multicodec(mc, pubkey))))

Non-circular authorities (R-16.1):
  - multiformats multicodec registry: sha2-256 = 0x12 (permanent); ed25519-pub = 0xed,
    mldsa-65-pub = 0x1211, mldsa-87-pub = 0x1212 (all key-type codes, draft status).
    Confirmed against https://github.com/multiformats/multicodec/blob/master/table.csv.
  - multibase base32 = RFC 4648 base32, lowercase, no padding, prefix "b".
  - multihash (RFC/spec): varint(code) || varint(len) || digest.
  - the input public keys are the independent NIST ACVP keyGen pk (ML-DSA-65/87, from
    vectors/cose/nist_acvp_mldsa.json) and the RFC 8032 §7.1 Ed25519 public key.
This constructor shares no code with impl/go or impl/rust. It also emits an NFC edge case
(design.md §3.1/§3.3): a non-NFC identity string that a verifier MUST reject (NonNFC).
"""
import base64
import hashlib
import io
import json
import os
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))

# multicodec key-type codes and the sha2-256 multihash code (from the multiformats registry).
CODE_ED25519 = 0xED
CODE_MLDSA65 = 0x1211
CODE_MLDSA87 = 0x1212
MH_SHA256 = 0x12

# COSE alg ids that select the multicodec (design.md §4.1 / §5.1).
ALG_MLDSA65 = -49
ALG_MLDSA87 = -50
ALG_ED25519 = -19

# RFC 8032 §7.1 TEST 1 Ed25519 public key (independent authority).
ED25519_PK = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"


def uvarint(n):
    """Unsigned LEB128 varint (multiformats varint)."""
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        if n:
            out.append(b | 0x80)
        else:
            out.append(b)
            return bytes(out)


def multicodec(code, key):
    return uvarint(code) + key


def multihash(code, digest):
    return uvarint(code) + uvarint(len(digest)) + digest


def base32_lower_nopad(data):
    return base64.b32encode(data).decode("ascii").lower().rstrip("=")


def signer_id(code, pubkey):
    tagged = multicodec(code, pubkey)
    mh = multihash(MH_SHA256, hashlib.sha256(tagged).digest())
    return "b" + base32_lower_nopad(mh)


def composite_signer_id(mldsa_code, mldsa_pub, ed_pub):
    """Composite signer id (design.md §5.1): the SHA-256 preimage is the multicodec-tagged
    ML-DSA public key concatenated with the multicodec-tagged Ed25519 public key, so stripping
    either leg changes the id. Uses only existing official multicodecs (no new code)."""
    preimage = multicodec(mldsa_code, mldsa_pub) + multicodec(CODE_ED25519, ed_pub)
    mh = multihash(MH_SHA256, hashlib.sha256(preimage).digest())
    return "b" + base32_lower_nopad(mh)


def build():
    nist = json.load(open(os.path.join(HERE, "..", "vectors", "cose", "nist_acvp_mldsa.json")))
    pk65 = bytes.fromhex(nist["keygen"]["ML-DSA-65"]["pk"])
    pk87 = bytes.fromhex(nist["keygen"]["ML-DSA-87"]["pk"])
    pk_ed = bytes.fromhex(ED25519_PK)

    signers = [
        {"name": "ML-DSA-65", "alg": ALG_MLDSA65, "multicodec": CODE_MLDSA65,
         "pubkey_hex": pk65.hex(), "signer_id": signer_id(CODE_MLDSA65, pk65)},
        {"name": "ML-DSA-87", "alg": ALG_MLDSA87, "multicodec": CODE_MLDSA87,
         "pubkey_hex": pk87.hex(), "signer_id": signer_id(CODE_MLDSA87, pk87)},
        {"name": "Ed25519", "alg": ALG_ED25519, "multicodec": CODE_ED25519,
         "pubkey_hex": pk_ed.hex(), "signer_id": signer_id(CODE_ED25519, pk_ed)},
    ]

    # NFC edge case (R-3.3): the identity string "café" — NFC (composed é, U+00E9) vs
    # NFD (e + combining acute, U+0065 U+0301). A verifier MUST accept NFC and reject NFD.
    nfc = unicodedata.normalize("NFC", "café")
    nfd = unicodedata.normalize("NFD", "café")
    assert nfc != nfd
    nfc_case = {
        "nfc_utf8_hex": nfc.encode("utf-8").hex(),
        "nfd_utf8_hex": nfd.encode("utf-8").hex(),
    }

    # Composite signer id (design.md §4.2/§5.1): derived from BOTH the ML-DSA-65 and the Ed25519
    # public key, so leg-stripping changes the id (=> SignerMismatch before verify). It reuses the
    # existing 0x1211 (ML-DSA-65) and 0xed (Ed25519) multicodecs — no new code point.
    composite = {
        "name": "COMPSIG-MLDSA65-Ed25519",
        "mldsa_alg": ALG_MLDSA65,
        "mldsa_multicodec": CODE_MLDSA65,
        "ed_multicodec": CODE_ED25519,
        "mldsa_pubkey_hex": pk65.hex(),
        "ed_pubkey_hex": pk_ed.hex(),
        "signer_id": composite_signer_id(CODE_MLDSA65, pk65, pk_ed),
    }

    return {
        "note": "Independent oracle output for N-AALP C4 (signer id + NFC + composite id). Go and "
                "Rust MUST reproduce every signer_id from its pubkey, reproduce the composite id from "
                "both keys, accept the NFC string, and reject the NFD string (NonNFC). Generated by "
                "tools/signerid_oracle.py; do not hand-edit.",
        "signers": signers,
        "composite": composite,
        "nfc": nfc_case,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "identity"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    for s in data["signers"]:
        print(s["name"], "->", s["signer_id"])
    print("wrote", path)


if __name__ == "__main__":
    main()
