# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""
N-AALP `stream.state` conformance oracle (design.md §10 state table; ietf/draft-bubblefish-naalp-01.md
"## Stream state machine" + "## Timers" -> "Stream idle/commit timer"). Constructs, from scratch,
the F3 non-circular reference for the streaming state-machine Guard (impl/go/streaming/streaming.go,
impl/rust/src/streaming.rs): every case's expected {valid, error, state} outcome is HARDCODED here,
read off the draft's normative table, and carries an inline comment naming the exact table row it
encodes. This oracle NEVER imports or calls the Guard — it does not know the implementation exists.

Each case drives ONE stream through an ordered `events` list; the graded outcome is the LAST event's
result (did it error, and with which named Kind) plus the stream's state after that last event. A
`commit` event always carries a `digest_hex`: for a "digest matches" case it is the independently
computed SHA-384 (python stdlib hashlib, RFC 6234) over the event's own chunk data — never anything
the Guard/CommitDigest produced — and for a "digest mismatch" case it is a deliberately wrong 48-byte
all-zero value that cannot equal a real SHA-384 output.

Table rows encoded (draft "## Stream state machine" + the Stream idle/commit timer under "##
Timers"):
  idle      + StreamOpen (effect authorized)     -> open
  idle      + StreamOpen (effect not authorized) -> reject EffectNotAuthorized (stays idle)
  open      + chunk                              -> open
  open      + StreamCheckpoint                   -> open
  open      + StreamCommit (digest matches)      -> committed
  open      + StreamCommit (digest mismatch)     -> reject StreamDigestMismatch (stays open)
  open      + StreamOpen                         -> reject StreamStateError (stays open)
  committed + {chunk, StreamCheckpoint, StreamCommit, StreamOpen} -> reject StreamStateError
  abandoned + {StreamOpen, chunk, StreamCheckpoint, StreamCommit} -> reject StreamStateError
  any other unlisted (state, event) pair          -> reject StreamStateError
  open      + expire (timer)                      -> abandoned
  non-open  + expire (idle/committed/abandoned)    -> reject StreamStateError (fail-closed, unchanged)

Generated by tools/streamstate_oracle.py; do not hand-edit vectors/streamstate/cases.json.
"""
import hashlib
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- fixed inputs shared across cases ----

CHUNK_DATA = b"payload"                     # single chunk, offset 0, used by every match-digest commit
CHUNK_DATA_HEX = CHUNK_DATA.hex()
MATCH_DIGEST_HEX = hashlib.sha384(CHUNK_DATA).hexdigest()   # independent SHA-384 (RFC 6234), not the Guard's
MISMATCH_DIGEST_HEX = "00" * 48             # a 48-byte value that cannot equal a real SHA-384 output

EFFECT_IDEMPOTENT_WRITE = 1                 # policy.IdempotentWrite / policy::IDEMPOTENT_WRITE
EFFECT_DESTRUCTIVE = 3                      # policy.Destructive / policy::DESTRUCTIVE
GRANTED_IDEMPOTENT_WRITE = 1                # ceiling authorizing IdempotentWrite (action <= ceiling)
GRANTED_READ_ONLY = 0                       # ceiling authorizing only ReadOnly (refuses Destructive)


def stream_id_hex(tc_id):
    """A stable, distinct stream id per test case (any hex; the oracle only needs it stable)."""
    return ("stream-tc%02d" % tc_id).encode("ascii").hex()


def ev_open(stream_hex, effect, granted):
    return {"ev": "open", "stream_hex": stream_hex, "effect": effect, "granted": granted}


def ev_open_auth(stream_hex):
    """The ordinary authorized open: effect=IdempotentWrite, granted=IdempotentWrite (1 <= 1)."""
    return ev_open(stream_hex, EFFECT_IDEMPOTENT_WRITE, GRANTED_IDEMPOTENT_WRITE)


def ev_chunk(stream_hex):
    return {"ev": "chunk", "stream_hex": stream_hex}


def ev_checkpoint(stream_hex):
    return {"ev": "checkpoint", "stream_hex": stream_hex}


def ev_commit(stream_hex, digest_hex):
    return {
        "ev": "commit",
        "stream_hex": stream_hex,
        "chunks": [{"offset": 0, "data_hex": CHUNK_DATA_HEX}],
        "digest_hex": digest_hex,
    }


def ev_commit_match(stream_hex):
    return ev_commit(stream_hex, MATCH_DIGEST_HEX)


def ev_commit_mismatch(stream_hex):
    return ev_commit(stream_hex, MISMATCH_DIGEST_HEX)


def ev_expire(stream_hex):
    return {"ev": "expire", "stream_hex": stream_hex}


def expect(valid, error, state):
    return {"valid": valid, "error": error, "state": state}


def build():
    cases = []

    def add(tc_id, name, table_row, events, expected):
        cases.append({
            "tcId": tc_id,
            "name": name,
            "table_row": table_row,
            "events": events,
            "expected": expected,
        })

    # 1: idle + StreamOpen (effect authorized) -> open
    sid = stream_id_hex(1)
    add(1, "idle+open(auth)", "idle | StreamOpen (effect authorized) | -> open",
        [ev_open_auth(sid)], expect(True, "", "open"))

    # 2: open + chunk -> open
    sid = stream_id_hex(2)
    add(2, "open+chunk", "open | chunk | -> open",
        [ev_open_auth(sid), ev_chunk(sid)], expect(True, "", "open"))

    # 3: open + StreamCheckpoint -> open
    sid = stream_id_hex(3)
    add(3, "open+checkpoint", "open | StreamCheckpoint | -> open",
        [ev_open_auth(sid), ev_checkpoint(sid)], expect(True, "", "open"))

    # 4: open + StreamCommit (digest matches) -> committed
    sid = stream_id_hex(4)
    add(4, "open+commit(match)", "open | StreamCommit (digest matches) | -> committed",
        [ev_open_auth(sid), ev_commit_match(sid)], expect(True, "", "committed"))

    # 5: idle + StreamOpen (effect not authorized) -> reject EffectNotAuthorized (stays idle)
    sid = stream_id_hex(5)
    add(5, "idle+open(not-auth)", "idle | StreamOpen (effect not authorized) | reject (EffectNotAuthorized)",
        [ev_open(sid, EFFECT_DESTRUCTIVE, GRANTED_READ_ONLY)],
        expect(False, "EffectNotAuthorized", "idle"))

    # 6: open + StreamCommit (digest mismatch) -> reject StreamDigestMismatch (stays open)
    sid = stream_id_hex(6)
    add(6, "open+commit(mismatch)", "open | StreamCommit (digest mismatch) | reject (StreamDigestMismatch)",
        [ev_open_auth(sid), ev_commit_mismatch(sid)],
        expect(False, "StreamDigestMismatch", "open"))

    # 7: open + StreamOpen -> reject StreamStateError (stays open)
    sid = stream_id_hex(7)
    add(7, "open+open", "open | StreamOpen | reject (StreamStateError)",
        [ev_open_auth(sid), ev_open_auth(sid)], expect(False, "StreamStateError", "open"))

    # 8: committed + chunk -> reject StreamStateError
    sid = stream_id_hex(8)
    add(8, "committed+chunk", "committed | chunk | reject (StreamStateError)",
        [ev_open_auth(sid), ev_commit_match(sid), ev_chunk(sid)],
        expect(False, "StreamStateError", "committed"))

    # 9: committed + StreamCheckpoint -> reject StreamStateError
    sid = stream_id_hex(9)
    add(9, "committed+checkpoint", "committed | StreamCheckpoint | reject (StreamStateError)",
        [ev_open_auth(sid), ev_commit_match(sid), ev_checkpoint(sid)],
        expect(False, "StreamStateError", "committed"))

    # 10: committed + StreamCommit -> reject StreamStateError
    sid = stream_id_hex(10)
    add(10, "committed+commit", "committed | StreamCommit | reject (StreamStateError)",
        [ev_open_auth(sid), ev_commit_match(sid), ev_commit_match(sid)],
        expect(False, "StreamStateError", "committed"))

    # 11: committed + StreamOpen -> reject StreamStateError (a committed id is never re-admitted)
    sid = stream_id_hex(11)
    add(11, "committed+open", "committed | StreamOpen | reject (StreamStateError)",
        [ev_open_auth(sid), ev_commit_match(sid), ev_open_auth(sid)],
        expect(False, "StreamStateError", "committed"))

    # 12: idle + chunk -> reject StreamStateError (unlisted-pair default)
    sid = stream_id_hex(12)
    add(12, "idle+chunk", "idle | chunk | reject (StreamStateError) [unlisted-pair default]",
        [ev_chunk(sid)], expect(False, "StreamStateError", "idle"))

    # 13: idle + StreamCheckpoint -> reject StreamStateError (unlisted-pair default)
    sid = stream_id_hex(13)
    add(13, "idle+checkpoint", "idle | StreamCheckpoint | reject (StreamStateError) [unlisted-pair default]",
        [ev_checkpoint(sid)], expect(False, "StreamStateError", "idle"))

    # 14: idle + StreamCommit -> reject StreamStateError (unlisted-pair default; state check fires
    # before the digest is inspected, so the commit's digest_hex is irrelevant here)
    sid = stream_id_hex(14)
    add(14, "idle+commit", "idle | StreamCommit | reject (StreamStateError) [unlisted-pair default]",
        [ev_commit_match(sid)], expect(False, "StreamStateError", "idle"))

    # 15: open + expire (timer) -> abandoned
    sid = stream_id_hex(15)
    add(15, "open+expire", "open | expire (timer) | -> abandoned [Stream idle/commit timer]",
        [ev_open_auth(sid), ev_expire(sid)], expect(True, "", "abandoned"))

    # 16: abandoned + StreamOpen -> reject StreamStateError (an abandoned id is never re-admitted)
    sid = stream_id_hex(16)
    add(16, "abandoned+open", "abandoned | StreamOpen | reject (StreamStateError)",
        [ev_open_auth(sid), ev_expire(sid), ev_open_auth(sid)],
        expect(False, "StreamStateError", "abandoned"))

    # 17: abandoned + chunk -> reject StreamStateError
    sid = stream_id_hex(17)
    add(17, "abandoned+chunk", "abandoned | chunk | reject (StreamStateError)",
        [ev_open_auth(sid), ev_expire(sid), ev_chunk(sid)],
        expect(False, "StreamStateError", "abandoned"))

    # 18: abandoned + StreamCheckpoint -> reject StreamStateError
    sid = stream_id_hex(18)
    add(18, "abandoned+checkpoint", "abandoned | StreamCheckpoint | reject (StreamStateError)",
        [ev_open_auth(sid), ev_expire(sid), ev_checkpoint(sid)],
        expect(False, "StreamStateError", "abandoned"))

    # 19: abandoned + StreamCommit -> reject StreamStateError
    sid = stream_id_hex(19)
    add(19, "abandoned+commit", "abandoned | StreamCommit | reject (StreamStateError)",
        [ev_open_auth(sid), ev_expire(sid), ev_commit_match(sid)],
        expect(False, "StreamStateError", "abandoned"))

    # 20: expire on idle -> reject StreamStateError, state unchanged (fail-closed; Timers section)
    sid = stream_id_hex(20)
    add(20, "expire-on-idle", "idle | expire | reject (StreamStateError) [fail-closed, Timers]",
        [ev_expire(sid)], expect(False, "StreamStateError", "idle"))

    # 21: expire on committed -> reject StreamStateError, state unchanged (the timer clears on commit)
    sid = stream_id_hex(21)
    add(21, "expire-on-committed", "committed | expire | reject (StreamStateError) [timer cleared on commit]",
        [ev_open_auth(sid), ev_commit_match(sid), ev_expire(sid)],
        expect(False, "StreamStateError", "committed"))

    # 22: expire on already-abandoned -> reject StreamStateError, state unchanged (terminal)
    sid = stream_id_hex(22)
    add(22, "expire-on-abandoned", "abandoned | expire | reject (StreamStateError) [terminal, fail-closed]",
        [ev_open_auth(sid), ev_expire(sid), ev_expire(sid)],
        expect(False, "StreamStateError", "abandoned"))

    return {
        "note": "Independent F3 non-circular oracle for N-AALP stream.state (design.md §10 state "
                "table + § Timers stream idle/commit timer). Every case drives one stream through an "
                "ordered `events` list on a fresh Guard; the graded outcome is the LAST event's "
                "{valid, error} plus the stream's final state. Expected outcomes are hardcoded here "
                "from the draft's normative table, never computed by calling Guard code. Generated by "
                "tools/streamstate_oracle.py; do not hand-edit.",
        "chunk_data_hex": CHUNK_DATA_HEX,
        "match_digest_hex": MATCH_DIGEST_HEX,
        "mismatch_digest_hex": MISMATCH_DIGEST_HEX,
        "cases": cases,
    }


def main():
    out_dir = os.path.normpath(os.path.join(HERE, "..", "vectors", "streamstate"))
    os.makedirs(out_dir, exist_ok=True)
    data = build()
    assert len(data["cases"]) == 22, "expected exactly 22 cases, got %d" % len(data["cases"])
    path = os.path.join(out_dir, "cases.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")
    for c in data["cases"]:
        print("  tc%02d %-24s -> %s" % (c["tcId"], c["name"], c["expected"]))
    print("wrote", path, "(%d cases)" % len(data["cases"]))


if __name__ == "__main__":
    main()
