# Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.
"""Repo-relative path + pinned-corpus helpers for the naalp-a2a-bridge test suite. No absolute
paths -- walks upward from this file, mirroring naalp_a2a_bridge._bootstrap and
ecosystem/naalp-bundle/tests/_paths.py's convention. Every loader here is READ-ONLY: this
package writes nothing outside ecosystem/naalp-a2a-bridge/ (the hard scope fence)."""
import json
import os


def _find_repo_root(start):
    d = os.path.abspath(start)
    for _ in range(8):
        if os.path.isfile(os.path.join(d, "vectors", "naming", "cases.json")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    raise RuntimeError("could not locate the naalp_draft-01 repo root "
                        "(vectors/naming/cases.json) by walking up from %r" % start)


REPO_ROOT = _find_repo_root(os.path.dirname(os.path.abspath(__file__)))


def load_naming_cases():
    """Independently load vectors/naming/cases.json -- the F3 non-circular oracle for C19 name
    bindings and the A2A task-state profile (design.md sec22), generated by
    tools/naming_oracle.py, a from-scratch model written against the design's own field layout
    and the A2A sec4.1.3 category rules that shares no code with impl/python/naalp/naming.py, or
    with naalp_a2a_bridge. Returns the parsed JSON dict unchanged. This bridge reads the SAME
    a2a.states / a2a.legal_edges / a2a.illegal_edges / a2a.card / a2a.transitions fixtures
    Part-1's own naming conformance suite grades against -- confirming this package's
    foreign-native state-name table and its produced wire bytes agree with the independent
    authority, not merely with naalp.naming's code."""
    path = os.path.join(REPO_ROOT, "vectors", "naming", "cases.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)
